{
 "title": "Lustre Group",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "fs_name",
    "label": "Filesystem Name",
    "query": "SHOW TAG VALUES FROM \"ost_kbytesinfo_free\" WITH KEY = fs_name"
   },
   { "name": "BARRELEYE_DATASOURCE_NAME", "query": "influxdb" }
  ]
 },
 "panels": [
  {
   "title": "I/O Throughput per Group",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "$tag_gid",
     "groupBy": [
      { "params": [ "gid" ], "type": "tag" }
     ],
     "measurement": "cqm_ost_jobstats_bytes-fs_name-gid",
     "query": "SELECT \"sum\" FROM \"cqm_ost_jobstats_bytes-fs_name-gid\" WHERE (\"fs_name\" = '$fs_name') AND $timeFilter GROUP BY \"gid\"",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" }
     ]
    }
   ]
  },
  {
   "title": "Write Throughput per Group",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "$tag_gid",
     "groupBy": [
      { "params": [ "gid" ], "type": "tag" }
     ],
     "measurement": "cqm_ost_jobstats_bytes-fs_name-gid-optype",
     "query": "SELECT sum(\"sum\") FROM \"cqm_ost_jobstats_bytes\" WHERE \"optype\" = 'sum_write_bytes' AND \"fs_name\" = '$fs_name' AND $timeFilter GROUP BY time(1m), \"job_id\" fill(null)",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "optype", "operator": "=", "value": "sum_write_bytes" },
      { "condition": "AND", "key": "fs_name", "operator": "=", "value": "$fs_name" }
     ]
    }
   ]
  },
  {
   "title": "Read Throughput per User",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "$tag_gid",
     "groupBy": [
      { "params": [ "gid" ], "type": "tag" }
     ],
     "measurement": "cqm_ost_jobstats_bytes-fs_name-gid-optype",
     "query": "SELECT sum(\"sum\") FROM \"cqm_ost_jobstats_bytes\" WHERE \"optype\" = 'sum_write_bytes' AND \"fs_name\" = '$fs_name' AND $timeFilter GROUP BY time(1m), \"job_id\" fill(null)",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "optype", "operator": "=", "value": "sum_read_bytes" },
      { "condition": "AND", "key": "fs_name", "operator": "=", "value": "$fs_name" }
     ]
    }
   ]
  },
  {
   "title": "Metadata Performance per Group",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "alias": "$tag_gid",
     "groupBy": [
      { "params": [ "gid" ], "type": "tag" }
     ],
     "measurement": "cqm_mdt_jobstats_samples-fs_name-gid",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" }
     ]
    }
   ]
  },
  {
   "title": "I/O Throughput per Group_",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_gid",
     "groupBy": [
      { "params": [ "gid" ], "type": "tag" }
     ],
     "measurement": "cqm_ost_jobstats_bytes-fs_name-gid",
     "query": "SELECT \"sum\" FROM \"cqm_ost_jobstats_bytes-fs_name-gid\" WHERE (\"fs_name\" = '$fs_name') AND $timeFilter GROUP BY \"gid\"",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" }
     ]
    }
   ]
  },
  {
   "title": "Metadata Performance per Group",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_gid",
     "groupBy": [
      { "params": [ "gid" ], "type": "tag" }
     ],
     "measurement": "cqm_mdt_jobstats_samples-fs_name-gid",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" }
     ]
    }
   ]
  }
 ]
}