{
 "title": "Lustre Statistics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "fs_name",
    "label": "Filesystem Name",
    "query": "SHOW TAG VALUES FROM \"ost_kbytesinfo_free\" WITH KEY = fs_name"
   },
   { "name": "BARRELEYE_DATASOURCE_NAME", "query": "influxdb" }
  ]
 },
 "panels": [
  {
   "title": "Free Capacity in Total",
   "type": "timeseries",
   "description": "Free capacity of the whole file system",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "alias": "Free Capacity",
     "groupBy": [
      { "params": [ "optype" ], "type": "tag" }
     ],
     "measurement": "cqm_ost_stats_bytes-optype-fs_name",
     "query": "SELECT \"sum\" FROM \"cqm_ost_kbytesinfo_free-fs_name\" WHERE \"fs_name\" = '$fs_name' AND $timeFilter",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" }
     ]
    }
   ]
  },
  {
   "title": "Used Capacity in Total",
   "type": "timeseries",
   "description": "Used capacity of the whole file system",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "alias": "Used Capacity",
     "groupBy": [
      { "params": [ "optype" ], "type": "tag" }
     ],
     "measurement": "cqm_ost_stats_bytes-optype-fs_name",
     "query": "SELECT \"sum\" FROM \"cqm_ost_kbytesinfo_used-fs_name\" WHERE \"fs_name\" = '$fs_name' AND $timeFilter",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" }
     ]
    }
   ]
  },
  {
   "title": "Free Capacity per OST",
   "type": "table",
   "description": "Free capacity on each OST.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "alias": "$tag_ost_index",
     "groupBy": [
      { "params": [ "exp_client" ], "type": "tag" }
     ],
     "measurement": "cqm_exp_md_stats",
     "query": "SELECT \"value\" FROM \"ost_kbytesinfo_free\" WHERE \"fs_name\" = '$fs_name' AND $timeFilter GROUP BY \"ost_index\"",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" }
     ]
    }
   ]
  },
  {
   "title": "Used Capacity per OST",
   "type": "table",
   "description": "Used capacity on each OST.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "alias": "$tag_ost_index",
     "groupBy": [
      { "params": [ "exp_client" ], "type": "tag" }
     ],
     "measurement": "cqm_exp_md_stats",
     "query": "SELECT \"value\" FROM \"ost_kbytesinfo_used\" WHERE \"fs_name\" = '$fs_name' AND $timeFilter GROUP BY \"ost_index\"",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" }
     ]
    }
   ]
  },
  {
   "title": "Used Capacity per User",
   "type": "table",
   "description": "The used capacity for each user.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "alias": "UID=$tag_user_id",
     "groupBy": [
      { "params": [ "user_id" ], "type": "tag" }
     ],
     "measurement": "cqm_ost_acctuser_samples-user_id0",
     "query": "SELECT \"sum\" FROM \"cqm_ost_acctuser_samples-fs_name-optype-user_id\" WHERE \"fs_name\" = '$fs_name' AND \"optype\" = 'usage_kbytes' AND $timeFilter GROUP BY \"user_id\"",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "optype", "operator": "=", "value": "usage_kbytes" }
     ]
    }
   ]
  },
  {
   "title": "Used Capacity per Group",
   "type": "table",
   "description": "The used capacity for each group.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "alias": "GID=$tag_group_id",
     "groupBy": [
      { "params": [ "group_id" ], "type": "tag" }
     ],
     "measurement": "cqm_ost_acctgroup_samples",
     "query": "SELECT \"sum\" FROM \"cqm_ost_acctgroup_samples-fs_name-group_id-optype\" WHERE \"fs_name\" = '$fs_name' AND \"optype\" = 'usage_kbytes' AND $timeFilter GROUP BY \"group_id\"",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "optype", "operator": "=", "value": "usage_kbytes" }
     ]
    }
   ]
  },
  {
   "title": "Free Inode Number in Total",
   "type": "timeseries",
   "description": "Free inode number of the whole file system",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Free Inode Number",
     "groupBy": [
      { "params": [ "optype" ], "type": "tag" }
     ],
     "measurement": "cqm_ost_stats_bytes-optype-fs_name",
     "query": "SELECT \"sum\" FROM \"cqm_mdt_filesinfo_free-fs_name\" WHERE \"fs_name\" = '$fs_name' AND $timeFilter",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" }
     ]
    }
   ]
  },
  {
   "title": "Used Inode Number in Total",
   "type": "timeseries",
   "description": "Used inode number of the whole file system",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Used Inode Number",
     "groupBy": [
      { "params": [ "optype" ], "type": "tag" }
     ],
     "measurement": "cqm_ost_stats_bytes-optype-fs_name",
     "query": "SELECT \"sum\" FROM \"cqm_mdt_filesinfo_used-fs_name\" WHERE \"fs_name\" = '$fs_name' AND $timeFilter",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" }
     ]
    }
   ]
  },
  {
   "title": "Free Inode Number per MDT",
   "type": "table",
   "description": "Free inode number on each MDT.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_mdt_index",
     "groupBy": [
      { "params": [ "exp_client" ], "type": "tag" }
     ],
     "measurement": "cqm_exp_md_stats",
     "query": "SELECT \"value\" FROM \"mdt_filesinfo_free\" WHERE \"fs_name\" = '$fs_name' AND $timeFilter GROUP BY \"mdt_index\"",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" }
     ]
    }
   ]
  },
  {
   "title": "Used Inode Number per User",
   "type": "table",
   "description": "The used inodes for each user.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "UID=$tag_user_id",
     "groupBy": [
      { "params": [ "user_id" ], "type": "tag" }
     ],
     "measurement": "cqm_mdt_acctuser_samples",
     "query": "SELECT \"sum\" FROM \"cqm_mdt_acctuser_samples-fs_name-optype-user_id\" WHERE \"fs_name\" = '$fs_name' AND \"optype\" = 'usage_inodes' AND $timeFilter GROUP BY \"user_id\"",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "optype", "operator": "=", "value": "usage_inodes" }
     ]
    }
   ]
  },
  {
   "title": "Used Inode Number per Group",
   "type": "table",
   "description": "The used inodes for each user.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "GID=$tag_group_id",
     "groupBy": [
      { "params": [ "group_id" ], "type": "tag" }
     ],
     "measurement": "cqm_mdt_acctgroup_samples",
     "query": "SELECT \"sum\" FROM \"cqm_mdt_acctgroup_samples-fs_name-group_id-optype\" WHERE \"fs_name\" = '$fs_name' AND \"optype\" = 'usage_inodes' AND $timeFilter GROUP BY \"group_id\"",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "optype", "operator": "=", "value": "usage_inodes" }
     ]
    }
   ]
  },
  {
   "title": "Used Inode Number per MDT",
   "type": "table",
   "description": "Used inode number on each MDT.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_mdt_index",
     "groupBy": [
      { "params": [ "exp_client" ], "type": "tag" }
     ],
     "measurement": "cqm_exp_md_stats",
     "query": "SELECT \"value\" FROM \"mdt_filesinfo_used\" WHERE \"fs_name\" = '$fs_name' AND $timeFilter GROUP BY \"mdt_index\"",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" }
     ]
    }
   ]
  },
  {
   "title": "I/O Throughput in Total",
   "type": "timeseries",
   "description": "I/O Throughput  of the whole file system",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "$tag_optype",
     "groupBy": [
      { "params": [ "optype" ], "type": "tag" }
     ],
     "measurement": "cqm_ost_stats_bytes-optype-fs_name",
     "query": "SELECT \"sum\" FROM \"cqm_ost_stats_bytes-fs_name-optype\" WHERE \"fs_name\" = '$fs_name' AND $timeFilter GROUP BY \"optype\"",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" }
     ]
    }
   ]
  },
  {
   "title": "I/O Throughput per OST",
   "type": "table",
   "description": "The I/O throughput for each OST.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "$tag_ost_index",
     "groupBy": [
      { "params": [ "ost_index" ], "type": "tag" }
     ],
     "measurement": "cqm_ost_stats_bytes-fs_name-ost_index",
     "query": "SELECT \"sum\" FROM \"cqm_ost_stats_bytes-fs_name-ost_index\" WHERE \"fs_name\" = '$fs_name' AND $timeFilter GROUP BY \"ost_index\"",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" }
     ]
    }
   ]
  },
  {
   "title": "Read Throughput per OST",
   "type": "table",
   "description": "The read throughput for each OST.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "$tag_ost_index",
     "groupBy": [
      { "params": [ "ost_index" ], "type": "tag" }
     ],
     "measurement": "ost_stats_bytes",
     "query": "SELECT \"sum\" FROM \"cqm_ost_stats_bytes-fs_name-optype-ost_index\" WHERE \"fs_name\" = '$fs_name' AND \"optype\" = 'sum_read_bytes' AND $timeFilter GROUP BY \"ost_index\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "optype", "operator": "=", "value": "read" }
     ]
    }
   ]
  },
  {
   "title": "Write Throughput per OST",
   "type": "table",
   "description": "The write throughput for each OST.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "$tag_ost_index",
     "groupBy": [
      { "params": [ "ost_index" ], "type": "tag" }
     ],
     "measurement": "ost_stats_bytes",
     "query": "SELECT \"sum\" FROM \"ost_stats_bytes\" WHERE \"fs_name\" = '$fs_name' AND \"optype\" = 'write' AND $timeFilter GROUP BY \"ost_index\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "optype", "operator": "=", "value": "write" }
     ]
    }
   ]
  },
  {
   "title": "Metadata Operation Rate in Total",
   "type": "timeseries",
   "description": "Metadata Operation Rate of the whole file system",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "alias": "Metadata Operation Rate",
     "groupBy": [
      { "params": [ "optype" ], "type": "tag" }
     ],
     "measurement": "cqm_ost_stats_bytes-optype-fs_name",
     "query": "SELECT \"sum\" FROM \"cqm_md_stats-fs_name\" WHERE \"fs_name\" = '$fs_name' AND $timeFilter",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" }
     ]
    }
   ]
  },
  {
   "title": "Metadata Operation Rate per MDT",
   "type": "table",
   "description": "The metadata operation  rate for each MDT.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "alias": "$tag_mdt_index",
     "groupBy": [
      { "params": [ "optype" ], "type": "tag" }
     ],
     "measurement": "cqm_md_stats-optype-fs_name",
     "query": "SELECT \"sum\" FROM \"cqm_md_stats-fs_name-mdt_index\" WHERE \"fs_name\" = '$fs_name' AND $timeFilter GROUP BY \"mdt_index\"",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" }
     ]
    }
   ]
  },
  {
   "title": "Metadata Operation Rate per Client",
   "type": "table",
   "description": "The metadata operation  rate for each client.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "alias": "$tag_mdt_exp_client",
     "groupBy": [
      { "params": [ "exp_client" ], "type": "tag" }
     ],
     "measurement": "cqm_exp_md_stats-exp_client-fs_name",
     "query": "SELECT \"sum\" FROM \"cqm_exp_md_stats-mdt_exp_client-fs_name\" WHERE (\"fs_name\" = '$fs_name') AND $timeFilter GROUP BY \"exp_client\"",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" }
     ]
    }
   ]
  },
  {
   "title": "Metadata Operation Rate per Type",
   "type": "table",
   "description": "The operation  rate for each type of metadata operation",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "alias": "$tag_optype",
     "groupBy": [
      { "params": [ "optype" ], "type": "tag" }
     ],
     "measurement": "cqm_md_stats-optype-fs_name",
     "query": "SELECT \"sum\" FROM \"cqm_md_stats-fs_name-optype\" WHERE \"fs_name\" = '$fs_name' AND $timeFilter GROUP BY \"optype\"",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" }
     ]
    }
   ]
  },
  {
   "title": "Write Bulk RPC Rate per Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "4k",
     "measurement": "cqm_ost_brw_stats_rpc_bulk_samples-field-fs_name-size",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "size", "operator": "=", "value": "1_pages" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "write_sample" },
      { "condition": "AND", "key": "fs_name", "operator": "=", "value": "$fs_name" }
     ]
    },
    {
     "alias": "8k",
     "measurement": "cqm_ost_brw_stats_rpc_bulk_samples-field-fs_name-size",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "size", "operator": "=", "value": "2_pages" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "write_sample" },
      { "condition": "AND", "key": "fs_name", "operator": "=", "value": "$fs_name" }
     ]
    },
    {
     "alias": "16k",
     "measurement": "cqm_ost_brw_stats_rpc_bulk_samples-field-fs_name-size",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "size", "operator": "=", "value": "4_pages" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "write_sample" },
      { "condition": "AND", "key": "fs_name", "operator": "=", "value": "$fs_name" }
     ]
    },
    {
     "alias": "32k",
     "measurement": "cqm_ost_brw_stats_rpc_bulk_samples-field-fs_name-size",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "size", "operator": "=", "value": "8_pages" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "write_sample" },
      { "condition": "AND", "key": "fs_name", "operator": "=", "value": "$fs_name" }
     ]
    },
    {
     "alias": "64k",
     "measurement": "cqm_ost_brw_stats_rpc_bulk_samples-field-fs_name-size",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "size", "operator": "=", "value": "16_pages" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "write_sample" },
      { "condition": "AND", "key": "fs_name", "operator": "=", "value": "$fs_name" }
     ]
    },
    {
     "alias": "128k",
     "measurement": "cqm_ost_brw_stats_rpc_bulk_samples-field-fs_name-size",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "size", "operator": "=", "value": "32_pages" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "write_sample" },
      { "condition": "AND", "key": "fs_name", "operator": "=", "value": "$fs_name" }
     ]
    },
    {
     "alias": "256k",
     "measurement": "cqm_ost_brw_stats_rpc_bulk_samples-field-fs_name-size",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "size", "operator": "=", "value": "64_pages" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "write_sample" },
      { "condition": "AND", "key": "fs_name", "operator": "=", "value": "$fs_name" }
     ]
    },
    {
     "alias": "512k",
     "measurement": "cqm_ost_brw_stats_rpc_bulk_samples-field-fs_name-size",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "size", "operator": "=", "value": "128_pages" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "write_sample" },
      { "condition": "AND", "key": "fs_name", "operator": "=", "value": "$fs_name" }
     ]
    },
    {
     "alias": "2m",
     "measurement": "cqm_ost_brw_stats_rpc_bulk_samples-field-fs_name-size",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "size", "operator": "=", "value": "512_pages" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "write_sample" },
      { "condition": "AND", "key": "fs_name", "operator": "=", "value": "$fs_name" }
     ]
    },
    {
     "alias": "1m",
     "measurement": "cqm_ost_brw_stats_rpc_bulk_samples-field-fs_name-size",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "size", "operator": "=", "value": "256_pages" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "write_sample" },
      { "condition": "AND", "key": "fs_name", "operator": "=", "value": "$fs_name" }
     ]
    },
    {
     "alias": "4m",
     "measurement": "cqm_ost_brw_stats_rpc_bulk_samples-field-fs_name-size",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "size", "operator": "=", "value": "1K_pages" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "write_sample" },
      { "condition": "AND", "key": "fs_name", "operator": "=", "value": "$fs_name" }
     ]
    },
    {
     "alias": "8m",
     "measurement": "cqm_ost_brw_stats_rpc_bulk_samples-field-fs_name-size",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "size", "operator": "=", "value": "2K_pages" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "write_sample" },
      { "condition": "AND", "key": "fs_name", "operator": "=", "value": "$fs_name" }
     ]
    },
    {
     "alias": "16m",
     "measurement": "cqm_ost_brw_stats_rpc_bulk_samples-field-fs_name-size",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "size", "operator": "=", "value": "4K_pages" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "write_sample" },
      { "condition": "AND", "key": "fs_name", "operator": "=", "value": "$fs_name" }
     ]
    }
   ]
  },
  {
   "title": "Size Distribution of Write Bulk RPC",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_size",
     "groupBy": [
      { "params": [ "size" ], "type": "tag" }
     ],
     "measurement": "cqm_ost_brw_stats_rpc_bulk_samples-field-fs_name-size",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "write_sample" }
     ]
    }
   ]
  },
  {
   "title": "Read Bulk RPC Rate per Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "4k",
     "measurement": "cqm_ost_brw_stats_rpc_bulk_samples-field-fs_name-size",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "size", "operator": "=", "value": "1_pages" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "read_sample" }
     ]
    },
    {
     "alias": "8k",
     "measurement": "cqm_ost_brw_stats_rpc_bulk_samples-field-fs_name-size",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "size", "operator": "=", "value": "2_pages" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "read_sample" }
     ]
    },
    {
     "alias": "16k",
     "measurement": "cqm_ost_brw_stats_rpc_bulk_samples-field-fs_name-size",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "size", "operator": "=", "value": "4_pages" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "read_sample" }
     ]
    },
    {
     "alias": "32k",
     "measurement": "cqm_ost_brw_stats_rpc_bulk_samples-field-fs_name-size",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "size", "operator": "=", "value": "8_pages" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "read_sample" }
     ]
    },
    {
     "alias": "64k",
     "measurement": "cqm_ost_brw_stats_rpc_bulk_samples-field-fs_name-size",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "size", "operator": "=", "value": "16_pages" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "read_sample" }
     ]
    },
    {
     "alias": "128k",
     "measurement": "cqm_ost_brw_stats_rpc_bulk_samples-field-fs_name-size",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "size", "operator": "=", "value": "32_pages" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "read_sample" }
     ]
    },
    {
     "alias": "256k",
     "measurement": "cqm_ost_brw_stats_rpc_bulk_samples-field-fs_name-size",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "size", "operator": "=", "value": "64_pages" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "read_sample" }
     ]
    },
    {
     "alias": "512k",
     "measurement": "cqm_ost_brw_stats_rpc_bulk_samples-field-fs_name-size",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "size", "operator": "=", "value": "128_pages" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "read_sample" }
     ]
    },
    {
     "alias": "2m",
     "measurement": "cqm_ost_brw_stats_rpc_bulk_samples-field-fs_name-size",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "size", "operator": "=", "value": "512_pages" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "read_sample" }
     ]
    },
    {
     "alias": "1m",
     "measurement": "cqm_ost_brw_stats_rpc_bulk_samples-field-fs_name-size",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "size", "operator": "=", "value": "256_pages" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "read_sample" }
     ]
    },
    {
     "alias": "4m",
     "measurement": "cqm_ost_brw_stats_rpc_bulk_samples-field-fs_name-size",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "size", "operator": "=", "value": "1K_pages" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "read_sample" }
     ]
    },
    {
     "alias": "8m",
     "measurement": "cqm_ost_brw_stats_rpc_bulk_samples-field-fs_name-size",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "size", "operator": "=", "value": "2K_pages" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "read_sample" }
     ]
    },
    {
     "alias": "16m",
     "measurement": "cqm_ost_brw_stats_rpc_bulk_samples-field-fs_name-size",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "size", "operator": "=", "value": "4K_pages" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "read_sample" }
     ]
    }
   ]
  },
  {
   "title": "Size Distribution of Read Bulk RPC",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_size",
     "groupBy": [
      { "params": [ "size" ], "type": "tag" }
     ],
     "measurement": "cqm_ost_brw_stats_rpc_bulk_samples-field-fs_name-size",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "read_sample" }
     ]
    }
   ]
  },
  {
   "title": "Distribution of Discontinuous Pages in Each Write I/O",
   "type": "piechart",
   "description": "If the next page to be written or read in the I/O is not with the next offset, that page is a discontinuous page. There could be multiple discontinuous pages in an I/O. I/Os with less discontinuous pages are more friendly to OSDs.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_size",
     "groupBy": [
      { "params": [ "size" ], "type": "tag" }
     ],
     "measurement": "cqm_ost_brw_stats_rpc_bulk_samples-field-fs_name-size",
     "query": "SELECT \"sum\" FROM \"cqm_ost_brw_stats_page_discontiguous_rpc_samples-field-fs_name-size\" WHERE \"fs_name\" = '$fs_name' AND \"field\" = 'write_sample' AND $timeFilter GROUP BY \"size\"",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "write_sample" }
     ]
    }
   ]
  },
  {
   "title": "Distribution of Discontinuous Pages in Each Read I/O",
   "type": "piechart",
   "description": "If the next page to be written or read in the I/O is not with the next offset, that page is a discontinuous page. There could be multiple discontinuous pages in an I/O. I/Os with less discontinuous pages are more friendly to OSDs.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_size",
     "groupBy": [
      { "params": [ "size" ], "type": "tag" }
     ],
     "measurement": "cqm_ost_brw_stats_rpc_bulk_samples-field-fs_name-size",
     "query": "SELECT \"sum\" FROM \"cqm_ost_brw_stats_page_discontiguous_rpc_samples-field-fs_name-size\" WHERE \"fs_name\" = '$fs_name' AND \"field\" = 'read_sample' AND $timeFilter GROUP BY \"size\"",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "write_sample" }
     ]
    }
   ]
  },
  {
   "title": "Distribution of Discontinuous Blocks in Each Write I/O",
   "type": "piechart",
   "description": "If the next block to be written or read in the I/O is not with the next offset, that block is a discontinuous block. There could be multiple discontinuous block in an I/O. I/Os with less discontinuous blocks are more friendly to OSDs. One page contains multiple blocks. The block size is determined by underline file system (Ldiskfs or ZFS).",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_size",
     "groupBy": [
      { "params": [ "size" ], "type": "tag" }
     ],
     "measurement": "cqm_ost_brw_stats_rpc_bulk_samples-field-fs_name-size",
     "query": "SELECT \"sum\" FROM \"cqm_ost_brw_stats_block_discontiguous_rpc_samples-field-fs_name-size\" WHERE \"fs_name\" = '$fs_name' AND \"field\" = 'write_sample' AND $timeFilter GROUP BY \"size\"",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "write_sample" }
     ]
    }
   ]
  },
  {
   "title": "Distribution of Discontinuous Blocks in Each Read I/O",
   "type": "piechart",
   "description": "If the next block to be written or read in the I/O is not with the next offset, that block is a discontinuous block. There could be multiple discontinuous block in an I/O. I/Os with less discontinuous blocks are more friendly to OSDs. One page contains multiple blocks. The block size is determined by underline file system (Ldiskfs or ZFS).",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_size",
     "groupBy": [
      { "params": [ "size" ], "type": "tag" }
     ],
     "measurement": "cqm_ost_brw_stats_rpc_bulk_samples-field-fs_name-size",
     "query": "SELECT \"sum\" FROM \"cqm_ost_brw_stats_block_discontiguous_rpc_samples-field-fs_name-size\" WHERE \"fs_name\" = '$fs_name' AND \"field\" = 'read_sample' AND $timeFilter GROUP BY \"size\"",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "write_sample" }
     ]
    }
   ]
  },
  {
   "title": "Distribution of Fragments in Each Write I/O",
   "type": "piechart",
   "description": "Sometimes an I/O is not able to be written/read in a single BIO on OST,  instead, multiple BIOs are submitted. The fragment number of this I/O equals to the BIO number. Usually, less fragments in the I/Os mean better performance.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_size",
     "groupBy": [
      { "params": [ "size" ], "type": "tag" }
     ],
     "measurement": "cqm_ost_brw_stats_rpc_bulk_samples-field-fs_name-size",
     "query": "SELECT \"sum\" FROM \"cqm_ost_brw_stats_fragmented_io_samples-field-fs_name-size\" WHERE \"fs_name\" = '$fs_name' AND \"field\" = 'write_sample' AND $timeFilter GROUP BY \"size\"",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "write_sample" }
     ]
    }
   ]
  },
  {
   "title": "Distribution of Fragments in Each Read I/O",
   "type": "piechart",
   "description": "Sometimes an I/O is not able to be written/read in a single BIO on OST,  instead, multiple BIOs are submitted. The fragment number of this I/O equals to the BIO number. Usually, less fragments in the I/Os mean better performance.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_size",
     "groupBy": [
      { "params": [ "size" ], "type": "tag" }
     ],
     "measurement": "cqm_ost_brw_stats_rpc_bulk_samples-field-fs_name-size",
     "query": "SELECT \"sum\" FROM \"cqm_ost_brw_stats_fragmented_io_samples-field-fs_name-size\" WHERE \"fs_name\" = '$fs_name' AND \"field\" = 'read_sample' AND $timeFilter GROUP BY \"size\"",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "write_sample" }
     ]
    }
   ]
  },
  {
   "title": "Distribution of In-fight Write I/O Number when Starting Each Write I/O",
   "type": "piechart",
   "description": "The in-flight I/O number means the BIO that have started but not ended yet. Thus, when starting a BIO, the in-flight I/O increases. By contrast, when a BIO ends, the in-flight I/O number decreases. And when starting a BIO, the current in-flight I/O number will be collected. More in-flight I/Os means more concurrent I/Os on this OST, and thus heavier load for the OST.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_size",
     "groupBy": [
      { "params": [ "size" ], "type": "tag" }
     ],
     "measurement": "cqm_ost_brw_stats_rpc_bulk_samples-field-fs_name-size",
     "query": "SELECT \"sum\" FROM \"cqm_ost_brw_stats_io_in_flight_samples-field-fs_name-size\" WHERE \"fs_name\" = '$fs_name' AND \"field\" = 'write_sample' AND $timeFilter GROUP BY \"size\"",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "write_sample" }
     ]
    }
   ]
  },
  {
   "title": "Distribution of In-fight Read I/O Number when Starting Each Read I/O",
   "type": "piechart",
   "description": "The in-flight I/O number means the BIO that have started but not ended yet. Thus, when starting a BIO, the in-flight I/O increases. By contrast, when a BIO ends, the in-flight I/O number decreases. And when starting a BIO, the current in-flight I/O number will be collected. More in-flight I/Os means more concurrent I/Os on this OST, and thus heavier load for the OST.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_size",
     "groupBy": [
      { "params": [ "size" ], "type": "tag" }
     ],
     "measurement": "cqm_ost_brw_stats_rpc_bulk_samples-field-fs_name-size",
     "query": "SELECT \"sum\" FROM \"cqm_ost_brw_stats_io_in_flight_samples-field-fs_name-size\" WHERE \"fs_name\" = '$fs_name' AND \"field\" = 'read_sample' AND $timeFilter GROUP BY \"size\"",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "write_sample" }
     ]
    }
   ]
  },
  {
   "title": "Distribution of Write I/O Time",
   "type": "piechart",
   "description": "The I/O time is the elasped time length between an I/O (Not BIO. A single I/O could sumbit multiple BIOs) starts and ends. Less I/O time of course is better.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_size",
     "groupBy": [
      { "params": [ "size" ], "type": "tag" }
     ],
     "measurement": "cqm_ost_brw_stats_rpc_bulk_samples-field-fs_name-size",
     "query": "SELECT \"sum\" FROM \"cqm_ost_brw_stats_io_time_samples-field-fs_name-size\" WHERE \"fs_name\" = '$fs_name' AND \"field\" = 'write_sample' AND $timeFilter GROUP BY \"size\"",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "write_sample" }
     ]
    }
   ]
  },
  {
   "title": "Distribution of Read I/O Time",
   "type": "piechart",
   "description": "The I/O time is the elasped time length between an I/O (Not BIO. A single I/O could sumbit multiple BIOs) starts and ends. Less I/O time of course is better.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_size",
     "groupBy": [
      { "params": [ "size" ], "type": "tag" }
     ],
     "measurement": "cqm_ost_brw_stats_rpc_bulk_samples-field-fs_name-size",
     "query": "SELECT \"sum\" FROM \"cqm_ost_brw_stats_io_time_samples-field-fs_name-size\" WHERE \"fs_name\" = '$fs_name' AND \"field\" = 'read_sample' AND $timeFilter GROUP BY \"size\"",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "write_sample" }
     ]
    }
   ]
  },
  {
   "title": "Distribution of Write I/O Size on Disk",
   "type": "piechart",
   "description": "The I/O size on disk is the size of submitted BIO. Usually, bigger I/O size means better performance.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_size",
     "groupBy": [
      { "params": [ "size" ], "type": "tag" }
     ],
     "measurement": "cqm_ost_brw_stats_rpc_bulk_samples-field-fs_name-size",
     "query": "SELECT \"sum\" FROM \"cqm_ost_brw_stats_io_size_samples-field-fs_name-size\" WHERE \"fs_name\" = '$fs_name' AND \"field\" = 'write_sample' AND $timeFilter GROUP BY \"size\"",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "write_sample" }
     ]
    }
   ]
  },
  {
   "title": "Distribution of Read I/O Size on Disk",
   "type": "piechart",
   "description": "The I/O size is the size of submitted BIO. Usually, bigger I/O size means better performance.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_size",
     "groupBy": [
      { "params": [ "size" ], "type": "tag" }
     ],
     "measurement": "cqm_ost_brw_stats_rpc_bulk_samples-field-fs_name-size",
     "query": "SELECT \"sum\" FROM \"cqm_ost_brw_stats_io_size_samples-field-fs_name-size\" WHERE \"fs_name\" = '$fs_name' AND \"field\" = 'read_sample' AND $timeFilter GROUP BY \"size\"",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "write_sample" }
     ]
    }
   ]
  },
  {
   "title": "Write Throughput per Client",
   "type": "table",
   "description": "The write throughput for each client.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "$tag_exp_client",
     "groupBy": [
      { "params": [ "exp_client" ], "type": "tag" }
     ],
     "measurement": "cqm_exp_ost_stats_bytes-exp_client-fs_name-optype",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "optype", "operator": "=", "value": "write" }
     ]
    }
   ]
  },
  {
   "title": "Read Throughput per Client",
   "type": "table",
   "description": "The read throughput for each client.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "$tag_exp_client",
     "groupBy": [
      { "params": [ "exp_client" ], "type": "tag" }
     ],
     "measurement": "cqm_exp_ost_stats_bytes-exp_client-fs_name-optype",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "optype", "operator": "=", "value": "read" }
     ]
    }
   ]
  },
  {
   "title": "I/O Throughput per Job",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "$tag_job_id",
     "groupBy": [
      { "params": [ "job_id" ], "type": "tag" }
     ],
     "measurement": "cqm_ost_jobstats_bytes-fs_name-job_id",
     "query": "SELECT sum(\"sum\") FROM \"cqm_ost_jobstats_bytes\" WHERE ( \"optype\" = 'sum_write_bytes' OR \"optype\" = 'sum_read_bytes' ) AND \"fs_name\" = '$fs_name' AND $timeFilter GROUP BY time(1m), \"job_id\" fill(null)",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" }
     ]
    }
   ]
  },
  {
   "title": "Write Throughput per Job",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "$tag_job_id",
     "groupBy": [
      { "params": [ "job_id" ], "type": "tag" }
     ],
     "measurement": "cqm_ost_jobstats_bytes-fs_name-job_id-optype",
     "query": "SELECT sum(\"sum\") FROM \"cqm_ost_jobstats_bytes\" WHERE \"optype\" = 'sum_write_bytes' AND \"fs_name\" = '$fs_name' AND $timeFilter GROUP BY time(1m), \"job_id\" fill(null)",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "optype", "operator": "=", "value": "sum_write_bytes" },
      { "condition": "AND", "key": "fs_name", "operator": "=", "value": "$fs_name" }
     ]
    }
   ]
  },
  {
   "title": "Read Throughput per Job",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "$tag_job_id",
     "groupBy": [
      { "params": [ "job_id" ], "type": "tag" }
     ],
     "measurement": "cqm_ost_jobstats_bytes-fs_name-job_id-optype",
     "query": "SELECT sum(\"sum\") FROM \"cqm_ost_jobstats_bytes\" WHERE ( \"optype\" = 'sum_write_bytes' OR \"optype\" = 'sum_read_bytes' ) AND \"fs_name\" = '$fs_name' AND $timeFilter GROUP BY time(1m), \"job_id\" fill(null)",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "optype", "operator": "=", "value": "sum_read_bytes" },
      { "condition": "AND", "key": "fs_name", "operator": "=", "value": "$fs_name" }
     ]
    }
   ]
  },
  {
   "title": "Metadata Performance per Job",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "alias": "$tag_job_id",
     "groupBy": [
      { "params": [ "job_id" ], "type": "tag" }
     ],
     "measurement": "cqm_mdt_jobstats_samples-fs_name-job_id",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" }
     ]
    }
   ]
  }
 ]
}