{
 "title": "Lustre MDT",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "fs_name",
    "label": "Filesystem Name",
    "query": "SHOW TAG VALUES FROM \"ost_kbytesinfo_free\" WITH KEY = fs_name"
   },
   {
    "name": "mdt_index",
    "label": "MDT Index",
    "query": "SHOW TAG VALUES FROM \"mdt_filesinfo_free\" WITH KEY = mdt_index WHERE \"fs_name\" = '$fs_name'"
   },
   { "name": "BARRELEYE_DATASOURCE_NAME", "label": "Datasource", "query": "influxdb" }
  ]
 },
 "panels": [
  {
   "title": "Free Inode Number",
   "type": "timeseries",
   "description": "Free Inode Number on this MDT.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Free Inode Number",
     "groupBy": [
      { "params": [ "optype" ], "type": "tag" }
     ],
     "measurement": "cqm_ost_stats_bytes-optype-fs_name",
     "query": "SELECT \"value\" FROM \"mdt_filesinfo_free\" WHERE \"fs_name\" = '$fs_name'  AND \"mdt_index\" = '$mdt_index' AND $timeFilter GROUP BY \"mdt_index\"",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" }
     ]
    }
   ]
  },
  {
   "title": "Used Inode Number",
   "type": "timeseries",
   "description": "Used Inode Number on this MDT.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Free Inode Number",
     "groupBy": [
      { "params": [ "optype" ], "type": "tag" }
     ],
     "measurement": "cqm_ost_stats_bytes-optype-fs_name",
     "query": "SELECT \"value\" FROM \"mdt_filesinfo_used\" WHERE \"fs_name\" = '$fs_name'  AND \"mdt_index\" = '$mdt_index' AND $timeFilter GROUP BY \"mdt_index\"",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" }
     ]
    }
   ]
  },
  {
   "title": "Used Inode Number per User",
   "type": "table",
   "description": "The used inode number for each user.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "UID=$tag_user_id",
     "groupBy": [
      { "params": [ "user_id" ], "type": "tag" }
     ],
     "measurement": "mdt_acctuser_samples",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "optype", "operator": "=", "value": "usage_inodes" },
      { "condition": "AND", "key": "mdt_index", "operator": "=", "value": "$mdt_index" }
     ]
    }
   ]
  },
  {
   "title": "Used Inode Number per Group",
   "type": "table",
   "description": "The used inode number for each group.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "GID=$tag_group_id",
     "groupBy": [
      { "params": [ "group_id" ], "type": "tag" }
     ],
     "measurement": "mdt_acctgroup_samples",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "optype", "operator": "=", "value": "usage_inodes" },
      { "condition": "AND", "key": "mdt_index", "operator": "=", "value": "$mdt_index" }
     ]
    }
   ]
  },
  {
   "title": "LDLM Lock Count",
   "type": "timeseries",
   "description": "LDLM lock number allocated on this MDT.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "LDLM Lock Count",
     "measurement": "mdt_lock_count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "mdt_index", "operator": "=", "value": "$mdt_index" }
     ]
    }
   ]
  },
  {
   "title": "LDLM Lock Timeouts",
   "type": "timeseries",
   "description": "Number of times this MDT evicted clients due to lack of reply to ASTs.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "LDLM Lock Timeouts",
     "measurement": "mdt_lock_timeouts",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "mdt_index", "operator": "=", "value": "$mdt_index" }
     ]
    }
   ]
  },
  {
   "title": "Number of Recovery Clients",
   "type": "timeseries",
   "description": "When Lustre OST/MDT service re-mounted, a recovery process will be started to recover the connections to the clients.\n\nevicted_clients: The number of clients that have been evicted during the recovery process.\n\nconnected_clients: The number of clients that connected successfully.\n\nrecoverable_clients: The maximum number of clients that can possibily be recovered.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_optype",
     "groupBy": [
      { "params": [ "optype" ], "type": "tag" }
     ],
     "measurement": "mdt_recovery_status",
     "query": "SELECT \"value\" FROM \"mdt_recovery_status\" WHERE (\"fs_name\" = '$fs_name' AND \"mdt_index\" = '$mdt_index') AND $timeFilter GROUP BY \"optype\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "mdt_index", "operator": "=", "value": "$mdt_index" }
     ]
    }
   ]
  }
 ]
}