{
 "title": "Lustre MDS",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "fs_name",
    "label": "Filesystem Name",
    "query": "SHOW TAG VALUES FROM \"mdt_filesinfo_free\" WITH KEY = fs_name"
   },
   {
    "name": "mds",
    "label": "MDS",
    "query": "SHOW TAG VALUES FROM \"mdt_filesinfo_free\" WITH KEY = fqdn WHERE \"fs_name\" = '$fs_name'"
   },
   { "name": "BARRELEYE_DATASOURCE_NAME", "query": "influxdb" }
  ]
 },
 "panels": [
  {
   "title": "Number of Active Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Minimum Number of Active Requests",
   "type": "timeseries",
   "description": "Active requests are the requests that is being actively handled by this MDS, not including the requests that are waiting in the queue. If the number of active requests is smaller than PTLRPC thread number minus two (one for incoming  request handling and the other for incoming high priority request handling), it generally means the thread number should be enough. The value shown in this graph is the minimum number during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Minimum Number of Active Requests",
     "measurement": "mdt_stats_req_active_min",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Average Number of Active Requests",
   "type": "timeseries",
   "description": "Active requests are the requests that is being actively handled by this MDS, not including the requests that are waiting in the queue. If the number of active requests is smaller than PTLRPC thread number minus two (one for incoming  request handling and the other for incoming high priority request handling), it generally means the thread number should be enough. The value shown in this graph is the average number during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Average Number of Active Requests",
     "measurement": "mdt_stats_req_active_mean",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Maximum Number of Active Requests",
   "type": "timeseries",
   "description": "Active requests are the requests that is being actively handled by this MDS, not including the requests that are waiting in the queue. If the number of active requests is smaller than PTLRPC thread number minus two (one for incoming  request handling and the other for incoming high priority request handling), it generally means the thread number should be enough. The value shown in this graph is the maximum number during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Maximum Number of Active Requests",
     "measurement": "mdt_stats_req_active_max",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Number of Incoming Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Minimum Number of Incoming Requests",
   "type": "timeseries",
   "description": "Incoming requests are the requests that waiting on preprocessing. A request is not incoming request any more when its proprocessing begins. And after preprocessing, the requests will be put into processing queue.  The value shown in this graph is the minimum number of incoming requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Minimum Number of Incoming Requests",
     "measurement": "mdt_stats_req_qdepth_min",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Average Number of Incoming Requests",
   "type": "timeseries",
   "description": "Incoming requests are the requests that waiting on preprocessing. A request is not incoming request any more when its proprocessing begins. And after preprocessing, the requests will be put into processing queue.  The value shown in this graph is the average number of incoming requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Average Number of Incoming Requests",
     "measurement": "mdt_stats_req_qdepth_mean",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Maximum Number of Incoming Requests",
   "type": "timeseries",
   "description": "Incoming requests are the requests that waiting on preprocessing. A request is not incoming request any more when its proprocessing begins. And after preprocessing, the requests will be put into processing queue.  The value shown in this graph is the maximum number of incoming requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Maximum Number of Incoming Requests",
     "measurement": "mdt_stats_req_qdepth_max",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Wait Time of Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Minimum Wait Time of Requests",
   "type": "timeseries",
   "description": "The wait time of a request is the time interval between its arrival time and the time when it starts to be handled. The value shown in this graph is the minimum wait time of the requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "Minimum Wait Time of Requests",
     "measurement": "mdt_stats_req_waittime_min",
     "query": "SELECT \"value\" * 1000 FROM \"mdt_stats_req_waittime_min\" WHERE (\"fqdn\" = '$mds') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Average Wait Time of Requests",
   "type": "timeseries",
   "description": "The wait time of a request is the time interval between its arrival time and the time when it starts to be handled. The value shown in this graph is the average wait time of the requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "Average Wait Time of Requests",
     "measurement": "mdt_stats_req_waittime_min",
     "query": "SELECT \"value\" * 1000 FROM \"mdt_stats_req_waittime_mean\" WHERE (\"fqdn\" = '$mds') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Maximum Wait Time of Requests",
   "type": "timeseries",
   "description": "The wait time of a request is the time interval between its arrival time and the time when it starts to be handled. The value shown in this graph is the maximum wait time of the requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "Maximum Wait Time of Requests",
     "measurement": "mdt_stats_req_waittime_max",
     "query": "SELECT \"value\" * 1000 FROM \"mdt_stats_req_waittime_max\" WHERE (\"fqdn\" = '$mds') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Adaptive Timeout Value",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Minimum Adaptive Timeout Value",
   "type": "timeseries",
   "description": "When a client sends a request, it has a timeout deadline for the reply. The timeout value of a service is an adaptive value negotiated between server and client during run-time. The value shown in this graph is the minimum timeout of the MDS service during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "Minimum Adaptive Timeout Value",
     "measurement": "mdt_stats_req_timeout_min",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Average Adaptive Timeout Value",
   "type": "timeseries",
   "description": "When a client sends a request, it has a timeout deadline for the reply. The timeout value of a service is an adaptive value negotiated between server and client during run-time. The value shown in this graph is the average timeout of the MDS service during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "Average Adaptive Timeout Value",
     "measurement": "mdt_stats_req_timeout_mean",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Maximum Adaptive Timeout Value",
   "type": "timeseries",
   "description": "When a client sends a request, it has a timeout deadline for the reply. The timeout value of a service is an adaptive value negotiated between server and client during run-time. The value shown in this graph is the maximum timeout of the OST service during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "Maximum Adaptive Timeout Value",
     "measurement": "mdt_stats_req_timeout_max",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Number of Available Request Buffers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Minimum Number of Available Request Buffers",
   "type": "timeseries",
   "description": "When a request arrives, one request buffer will be used. When number of available request buffers is under low water, more buffers are needed to avoid performance bottleneck. The value shown in this graph is the minimum number during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Minimum Number of Available Request Buffers",
     "measurement": "mdt_stats_reqbuf_avail_min",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Average Number of Available Request Buffers",
   "type": "timeseries",
   "description": "When a request arrives, one request buffer will be used. When number of available request buffers is under low water, more buffers are needed to avoid performance bottleneck. The value shown in this graph is the average number during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Average Number of Available Request Buffers",
     "measurement": "mdt_stats_reqbuf_avail_mean",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Maximum Number of Available Request Buffers",
   "type": "timeseries",
   "description": "When a request arrives, one request buffer will be used. When number of available request buffers is under low water, more buffers are needed to avoid performance bottleneck. The value shown in this graph is the maximum number during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Maximum Number of Available Request Buffers",
     "measurement": "mdt_stats_reqbuf_avail_max",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Handling Time of LDLM Ibits Enqueue Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Minimum Handing Time of LDLM Ibits Enqueue Requests",
   "type": "timeseries",
   "description": "The handling time of a request is the time interval between the time that it is started to be handled time and the time the handling finishes.  The value shown in this graph is the minimum handling time of the LDLM ibits enqueue requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "Minimum Handing Time of LDLM Ibits Enqueue Requests",
     "measurement": "mdt_stats_ldlm_ibits_enqueue_min",
     "query": "SELECT \"value\" * 1000 FROM \"mdt_stats_ldlm_ibits_enqueue_min\" WHERE (\"fqdn\" = '$mds') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Average Handing Time of LDLM Ibits Enqueue Requests",
   "type": "timeseries",
   "description": "The handling time of a request is the time interval between the time that it is started to be handled time and the time the handling finishes.  The value shown in this graph is the average handling time of the LDLM ibits enqueue requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "Average Handing Time of LDLM Ibits Enqueue Requests",
     "measurement": "mdt_stats_ldlm_ibits_enqueue_min",
     "query": "SELECT \"value\" * 1000 FROM \"mdt_stats_ldlm_ibits_enqueue_mean\" WHERE (\"fqdn\" = '$mds') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Maximum Handing Time of LDLM Ibits Enqueue Requests",
   "type": "timeseries",
   "description": "The handling time of a request is the time interval between the time that it is started to be handled time and the time the handling finishes.  The value shown in this graph is the maximum handling time of the LDLM ibits enqueue requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "Maximum Handing Time of LDLM Ibites Enqueue Requests",
     "measurement": "mdt_stats_ldlm_ibits_enqueue_max",
     "query": "SELECT \"value\" * 1000 FROM \"mdt_stats_ldlm_ibits_enqueue_max\" WHERE (\"fqdn\" = '$mds') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Handling Time of Getattr Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Minimum Handing Time of Getattr Requests",
   "type": "timeseries",
   "description": "The handling time of a request is the time interval between the time that it is started to be handled time and the time the handling finishes.  The value shown in this graph is the minimum handling time of the getattr requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "Minimum Handing Time of Getattr Requests",
     "measurement": "mdt_stats_mds_getattr_min",
     "query": "SELECT \"value\" * 1000 FROM \"mdt_stats_mds_getattr_min\" WHERE (\"fqdn\" = '$mds') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Average Handing Time of Getattr Requests",
   "type": "timeseries",
   "description": "The handling time of a request is the time interval between the time that it is started to be handled time and the time the handling finishes.  The value shown in this graph is the average handling time of the getattr requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "Average Handing Time of Getattr Requests",
     "measurement": "mdt_stats_mds_getattr_max",
     "query": "SELECT \"value\" * 1000 FROM \"mdt_stats_mds_getattr_mean\" WHERE (\"fqdn\" = '$mds') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Maximum Handing Time of Getattr Requests",
   "type": "timeseries",
   "description": "The handling time of a request is the time interval between the time that it is started to be handled time and the time the handling finishes.  The value shown in this graph is the maximum handling time of the getattr requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "Maximum Handing Time of Getattr Requests",
     "measurement": "mdt_stats_mds_getattr_max",
     "query": "SELECT \"value\" * 1000 FROM \"mdt_stats_mds_getattr_max\" WHERE (\"fqdn\" = '$mds') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Handling Time of Connect Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Minimum Handing Time of Connect Requests",
   "type": "timeseries",
   "description": "The handling time of a request is the time interval between the time that it is started to be handled time and the time the handling finishes.  The value shown in this graph is the minimum handling time of the connect requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "Minimum Handing Time of Connect Requests",
     "measurement": "mdt_stats_mds_connect_min",
     "query": "SELECT \"value\" * 1000 FROM \"mdt_stats_mds_connect_min\" WHERE (\"fqdn\" = '$mds') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Average Handing Time of Connect Requests",
   "type": "timeseries",
   "description": "The handling time of a request is the time interval between the time that it is started to be handled time and the time the handling finishes.  The value shown in this graph is the average handling time of the connect requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "Average Handing Time of Connect Requests",
     "measurement": "mdt_stats_mds_connect_max",
     "query": "SELECT \"value\" * 1000 FROM \"mdt_stats_mds_connect_mean\" WHERE (\"fqdn\" = '$mds') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Maximum Handing Time of Connect Requests",
   "type": "timeseries",
   "description": "The handling time of a request is the time interval between the time that it is started to be handled time and the time the handling finishes.  The value shown in this graph is the maximum handling time of the connect requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "Maximum Handing Time of Connect Requests",
     "measurement": "mdt_stats_mds_connect_max",
     "query": "SELECT \"value\" * 1000 FROM \"mdt_stats_mds_connect_max\" WHERE (\"fqdn\" = '$mds') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Handling Time of Get-root Request",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Minimum Handing Time of Get-root Requests",
   "type": "timeseries",
   "description": "The handling time of a request is the time interval between the time that it is started to be handled time and the time the handling finishes.  The value shown in this graph is the minimum handling time of the get-root requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "Minimum Handing Time of Get-root Requests",
     "measurement": "mdt_stats_mds_get_root_min",
     "query": "SELECT \"value\" * 1000 FROM \"mdt_stats_mds_get_root_min\" WHERE (\"fqdn\" = '$mds') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Average Handing Time of Get-root Requests",
   "type": "timeseries",
   "description": "The handling time of a request is the time interval between the time that it is started to be handled time and the time the handling finishes.  The value shown in this graph is the average handling time of the get-root requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "Average Handing Time of Get-root Requests",
     "measurement": "mdt_stats_mds_get_root_min",
     "query": "SELECT \"value\" * 1000 FROM \"mdt_stats_mds_get_root_mean\" WHERE (\"fqdn\" = '$mds') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Maximum Handing Time of Get-root Requests",
   "type": "timeseries",
   "description": "The handling time of a request is the time interval between the time that it is started to be handled time and the time the handling finishes.  The value shown in this graph is the maximum handling time of the get-root requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "Maximum Handing Time of Get-root Requests",
     "measurement": "mdt_stats_mds_get_root_max",
     "query": "SELECT \"value\" * 1000 FROM \"mdt_stats_mds_get_root_max\" WHERE (\"fqdn\" = '$mds') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Handling Time of Statfs Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Minimum Handing Time of Statfs Requests",
   "type": "timeseries",
   "description": "The handling time of a request is the time interval between the time that it is started to be handled time and the time the handling finishes.  The value shown in this graph is the minimum handling time of the statfs requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "Minimum Handing Time of Statfs Requests",
     "measurement": "mdt_stats_mds_statfs_min",
     "query": "SELECT \"value\" * 1000 FROM \"mdt_stats_mds_statfs_min\" WHERE (\"fqdn\" = '$mds') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Average Handing Time of Statfs Requests",
   "type": "timeseries",
   "description": "The handling time of a request is the time interval between the time that it is started to be handled time and the time the handling finishes.  The value shown in this graph is the average handling time of the statfs requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "Average Handing Time of Statfs Requests",
     "measurement": "mdt_stats_mds_statfs_max",
     "query": "SELECT \"value\" * 1000 FROM \"mdt_stats_mds_statfs_mean\" WHERE (\"fqdn\" = '$mds') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Maximum Handing Time of Statfs Requests",
   "type": "timeseries",
   "description": "The handling time of a request is the time interval between the time that it is started to be handled time and the time the handling finishes.  The value shown in this graph is the maximum handling time of the statfs requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "Maximum Handing Time of Statfs Requests",
     "measurement": "mdt_stats_mds_statfs_max",
     "query": "SELECT \"value\" * 1000 FROM \"mdt_stats_mds_statfs_max\" WHERE (\"fqdn\" = '$mds') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Handling Time of Getxattr Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Minimum Handing Time of Getxattr Requests",
   "type": "timeseries",
   "description": "The handling time of a request is the time interval between the time that it is started to be handled time and the time the handling finishes.  The value shown in this graph is the minimum handling time of the getxattr requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "Minimum Handing Time of Getxattr Requests",
     "measurement": "mdt_stats_mds_getxattr_min",
     "query": "SELECT \"value\" * 1000 FROM \"mdt_stats_mds_getxattr_min\" WHERE (\"fqdn\" = '$mds') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Average Handing Time of Getxattr Requests",
   "type": "timeseries",
   "description": "The handling time of a request is the time interval between the time that it is started to be handled time and the time the handling finishes.  The value shown in this graph is the average handling time of the getxattr requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "Average Handing Time of Getxattr Requests",
     "measurement": "mdt_stats_mds_getxattr_max",
     "query": "SELECT \"value\" * 1000 FROM \"mdt_stats_mds_getxattr_mean\" WHERE (\"fqdn\" = '$mds') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Maximum Handing Time of Getxattr Requests",
   "type": "timeseries",
   "description": "The handling time of a request is the time interval between the time that it is started to be handled time and the time the handling finishes.  The value shown in this graph is the maximum handling time of the getxattr requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "Maximum Handing Time of Getxattr Requests",
     "measurement": "mdt_stats_mds_getxattr_max",
     "query": "SELECT \"value\" * 1000 FROM \"mdt_stats_mds_getxattr_max\" WHERE (\"fqdn\" = '$mds') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Handling Time of Ping Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 99 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Minimum Handing Time of Ping Requests",
   "type": "timeseries",
   "description": "The handling time of a request is the time interval between the time that it is started to be handled time and the time the handling finishes.  The value shown in this graph is the minimum handling time of the ping requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "Minimum Handing Time of Ping Requests",
     "measurement": "mdt_stats_obd_ping_min",
     "query": "SELECT \"value\" * 1000 FROM \"mdt_stats_obd_ping_min\" WHERE (\"fqdn\" = '$mds') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Average Handing Time of Ping Requests",
   "type": "timeseries",
   "description": "The handling time of a request is the time interval between the time that it is started to be handled time and the time the handling finishes.  The value shown in this graph is the average handling time of the ping requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "Average Handing Time of Ping Requests",
     "measurement": "mdt_stats_obd_ping_min",
     "query": "SELECT \"value\" * 1000 FROM \"mdt_stats_obd_ping_mean\" WHERE (\"fqdn\" = '$mds') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Maximum Handing Time of Ping Requests",
   "type": "timeseries",
   "description": "The handling time of a request is the time interval between the time that it is started to be handled time and the time the handling finishes.  The value shown in this graph is the maximum handling time of the ping requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "Maximum Handing Time of Ping Requests",
     "measurement": "mdt_stats_obd_ping_max",
     "query": "SELECT \"value\" * 1000 FROM \"mdt_stats_obd_ping_max\" WHERE (\"fqdn\" = '$mds') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Number of Active Readpage Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 108 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Minimum Number of Active Readpage Requests",
   "type": "timeseries",
   "description": "Active requests are the requests that is being actively handled by this MDS, not including the requests that are waiting in the queue.   If the number of active requests is smaller than PTLRPC thread number minus two (one for incoming  request handling and the other for incoming high priority request handling), it generally means the thread number should be enough. The value shown in this graph is the minimum number during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Minimum Number of Active Readpage Requests",
     "measurement": "mdt_readpage_stats_req_active_min",
     "query": "SELECT \"value\" FROM \"mdt_readpage_stats_req_active_min\" WHERE (\"fqdn\" = '$mds') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Average Number of Active Readpage Requests",
   "type": "timeseries",
   "description": "Active requests are the requests that is being actively handled by this MDS, not including the requests that are waiting in the queue.   If the number of active requests is smaller than PTLRPC thread number minus two (one for incoming  request handling and the other for incoming high priority request handling), it generally means the thread number should be enough. The value shown in this graph is the average number during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Average Number of Active Readpage Requests",
     "measurement": "mdt_readpage_stats_req_active_mean",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Maximum Number of Active Readpage Requests",
   "type": "timeseries",
   "description": "Active requests are the requests that is being actively handled by  MDS, not including the requests that are waiting in the queue.   If the number of active requests is smaller than PTLRPC thread number minus two (one for incoming  request handling and the other for incoming high priority request handling), it generally means the thread number should be enough. The value shown in this graph is the maximum number during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Maximum Number of Active Readpage Requests",
     "measurement": "mdt_readpage_stats_req_active_max",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Number of Incoming Readpage Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 117 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Maximum Number of Incoming Readpage Requests",
   "type": "timeseries",
   "description": "Incoming requests are the requests that waiting on preprocessing. A request is not incoming request any more when its proprocessing begins. And after preprocessing, the requests will be put into processing queue.  The value shown in this graph is the maximum number of incoming requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Maximum Number of Incoming Readpage Requests",
     "measurement": "mdt_readpage_stats_req_qdepth_max",
     "query": "SELECT \"value\" FROM \"mdt_readpage_stats_req_qdepth_max\" WHERE (\"fqdn\" = '$mds') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Minimum Number of Incoming Readpage Requests",
   "type": "timeseries",
   "description": "Incoming requests are the requests that waiting on preprocessing. A request is not incoming request any more when its proprocessing begins. And after preprocessing, the requests will be put into processing queue.  The value shown in this graph is the minimum number of incoming requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Minimum Number of Incoming Readpage Requests",
     "measurement": "mdt_readpage_stats_req_qdepth_min",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Average Number of Incoming Readpage Requests",
   "type": "timeseries",
   "description": "Incoming requests are the requests that waiting on preprocessing. A request is not incoming request any more when its proprocessing begins. And after preprocessing, the requests will be put into processing queue.  The value shown in this graph is the average number of incoming requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Average Number of Incoming Readpage Requests",
     "measurement": "mdt_readpage_stats_req_qdepth_mean",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Wait Time of Readpage Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 126 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Minimum Wait Time of Readpage Requests",
   "type": "timeseries",
   "description": "The wait time of a request is the time interval between its arrival time and the time when it starts to be handled. The value shown in this graph is the minimum wait time of the requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "Minimum Wait Time of Readpage Requests",
     "measurement": "mdt_readpage_stats_req_waittime_min",
     "query": "SELECT \"value\" * 1000 FROM \"mdt_readpage_stats_req_waittime_min\" WHERE (\"fqdn\" = '$mds') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Average Wait Time of Readpage Requests",
   "type": "timeseries",
   "description": "The wait time of a request is the time interval between its arrival time and the time when it starts to be handled. The value shown in this graph is the average wait time of the requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "Average Wait Time of Readpage Requests",
     "measurement": "mdt_readpage_stats_req_waittime_min",
     "query": "SELECT \"value\" * 1000 FROM \"mdt_readpage_stats_req_waittime_mean\" WHERE (\"fqdn\" = '$mds') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Maximum Wait Time of Readpage Requests",
   "type": "timeseries",
   "description": "The wait time of a request is the time interval between its arrival time and the time when it starts to be handled.  The value shown in this graph is the maximum wait time of the requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "Maximum Wait Time of Readpage Requests",
     "measurement": "mdt_readpage_stats_req_waittime_max",
     "query": "SELECT \"value\" * 1000 FROM \"mdt_readpage_stats_req_waittime_max\" WHERE (\"fqdn\" = '$mds') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Adaptive Timeout Value of Readpage Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 135 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Minimum Adaptive Timeout Value of Readpage Service",
   "type": "timeseries",
   "description": "When a client sends a request, it has a timeout deadline for the reply. The timeout value of a service is an adaptive value negotiated between server and client during run-time. The value shown in this graph is the minimum timeout of the MDS readpage service during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 136 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "Minimum Adaptive Timeout Value of Readpage Service",
     "measurement": "mdt_readpage_stats_req_timeout_min",
     "query": "SELECT \"value\" FROM \"mdt_readpage_stats_req_timeout_min\" WHERE (\"fqdn\" = '$mds') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Average Adaptive Timeout Value of Readpage Service",
   "type": "timeseries",
   "description": "When a client sends a request, it has a timeout deadline for the reply. The timeout value of a service is an adaptive value negotiated between server and client during run-time. The value shown in this graph is the average timeout of the MDS readpage service during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 136 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "Average Adaptive Timeout Value of Readpage Service",
     "measurement": "mdt_readpage_stats_req_timeout_mean",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Maximum Adaptive Timeout Value of Readpage Service",
   "type": "timeseries",
   "description": "When a client sends a request, it has a timeout deadline for the reply. The timeout value of a service is an adaptive value negotiated between server and client during run-time. The value shown in this graph is the maximum timeout of the MDS readpage service during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 136 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "Maximum Adaptive Timeout Value of Readpage Service",
     "measurement": "mdt_readpage_stats_req_timeout_max",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Number of Available Readpage Request Buffers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 144 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Minimum Number of Available Readpage Request Buffers",
   "type": "timeseries",
   "description": "When a request arrives, one request buffer will be used. When number of available request buffers is under low water, more buffers are needed to avoid performance bottleneck. The value shown in this graph is the minimum number during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Minimum Number of Available Readpage Request Buffers",
     "measurement": "mdt_readpage_stats_reqbuf_avail_min",
     "query": "SELECT \"value\" FROM \"mdt_readpage_stats_reqbuf_avail_min\" WHERE (\"fqdn\" = '$mds') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Average Number of Available Readpage Request Buffers",
   "type": "timeseries",
   "description": "When a request arrives, one request buffer will be used. When number of available request buffers is under low water, more buffers are needed to avoid performance bottleneck. The value shown in this graph is the average number during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Average Number of Available Readpage Request Buffers",
     "measurement": "mdt_readpage_stats_reqbuf_avail_mean",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Maximum Number of Available Readpage Request Buffers",
   "type": "timeseries",
   "description": "When a request arrives, one request buffer will be used. When number of available request buffers is under low water, more buffers are needed to avoid performance bottleneck. The value shown in this graph is the maximum number during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Maximum Number of Available Readpage Request Buffers",
     "measurement": "mdt_readpage_stats_reqbuf_avail_max",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Handling Time of Close Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 153 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Minimum Handing Time of Close Requests",
   "type": "timeseries",
   "description": "The handling time of a request is the time interval between the time that it is started to be handled time and the time the handling finishes.  The value shown in this graph is the minimum handling time of the close requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 154 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "Minimum Handing Time of Close Requests",
     "measurement": "mdt_readpage_stats_mds_close_min",
     "query": "SELECT \"value\" * 1000 FROM \"mdt_readpage_stats_mds_close_min\" WHERE (\"fqdn\" = '$mds') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Average Handing Time of Close Requests",
   "type": "timeseries",
   "description": "The handling time of a request is the time interval between the time that it is started to be handled time and the time the handling finishes.  The value shown in this graph is the average handling time of the close requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 154 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "Average Handing Time of Close Requests",
     "measurement": "mdt_readpage_stats_mds_close_max",
     "query": "SELECT \"value\" * 1000 FROM \"mdt_readpage_stats_mds_close_mean\" WHERE (\"fqdn\" = '$mds') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Maximum Handing Time of Close Requests",
   "type": "timeseries",
   "description": "The handling time of a request is the time interval between the time that it is started to be handled time and the time the handling finishes.  The value shown in this graph is the maximum handling time of the close requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 154 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "Maximum Handing Time of Close Requests",
     "measurement": "mdt_readpage_stats_mds_close_max",
     "query": "SELECT \"value\" * 1000 FROM \"mdt_readpage_stats_mds_close_max\" WHERE (\"fqdn\" = '$mds') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Handling Time of Readpage Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 162 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Minimum Handing Time of Readpage Requests",
   "type": "timeseries",
   "description": "The handling time of a request is the time interval between the time that it is started to be handled time and the time the handling finishes.  The value shown in this graph is the minimum handling time of the readpage requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 163 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "Minimum Handing Time of Readpage Requests",
     "measurement": "mdt_readpage_stats_mds_readpage_min",
     "query": "SELECT \"value\" * 1000 FROM \"mdt_readpage_stats_mds_readpage_min\" WHERE (\"fqdn\" = '$mds') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Average Handing Time of Readpage Requests",
   "type": "timeseries",
   "description": "The handling time of a request is the time interval between the time that it is started to be handled time and the time the handling finishes.  The value shown in this graph is the average handling time of the readpage requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 163 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "Average Handing Time of Readpage Requests",
     "measurement": "mdt_readpage_stats_mds_readpage_max",
     "query": "SELECT \"value\" * 1000 FROM \"mdt_readpage_stats_mds_readpage_mean\" WHERE (\"fqdn\" = '$mds') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Maximum Handing Time of Readpage Requests",
   "type": "timeseries",
   "description": "The handling time of a request is the time interval between the time that it is started to be handled time and the time the handling finishes.  The value shown in this graph is the maximum handling time of the readpage requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 163 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "Maximum Handing Time of Readpage Requests",
     "measurement": "mdt_readpage_stats_mds_readpage_max",
     "query": "SELECT \"value\" * 1000 FROM \"mdt_readpage_stats_mds_readpage_max\" WHERE (\"fqdn\" = '$mds') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Number of Active LDLM Canceld Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 171 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Minimum Number of Active LDLM Canceld Requests",
   "type": "timeseries",
   "description": "Active requests are the requests that is being actively handled, not including the requests that are waiting in the queue.   If the number of active requests is smaller than PTLRPC thread number minus two (one for incoming  request handling and the other for incoming high priority request handling), it generally means the thread number should be enough. The value shown in this graph is the minimum number during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 172 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Minimum Number of Active LDLM Canceld Requests",
     "measurement": "ldlm_canceld_stats_req_active_min",
     "query": "SELECT \"value\" FROM \"ldlm_canceld_stats_req_active_min\" WHERE (\"fqdn\" = '$mds') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Average Number of Active LDLM Canceld Requests",
   "type": "timeseries",
   "description": "Active requests are the requests that is being actively handled, not including the requests that are waiting in the queue.   If the number of active requests is smaller than PTLRPC thread number minus two (one for incoming  request handling and the other for incoming high priority request handling), it generally means the thread number should be enough. The value shown in this graph is the average number during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 172 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Average Number of Active LDLM Canceld Requests",
     "measurement": "ldlm_canceld_stats_req_active_mean",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Maximum Number of Active LDLM Canceld Requests",
   "type": "timeseries",
   "description": "Active requests are the requests that is being actively handled, not including the requests that are waiting in the queue.   If the number of active requests is smaller than PTLRPC thread number minus two (one for incoming  request handling and the other for incoming high priority request handling), it generally means the thread number should be enough. The value shown in this graph is the maximum number during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 172 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Maximum Number of Active LDLM Canceld Requests",
     "measurement": "ldlm_canceld_stats_req_active_max",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Number of Incoming LDLM Canceld Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 180 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Minimum Number of Incoming LDLM Canceld Requests",
   "type": "timeseries",
   "description": "Incoming requests are the requests that waiting on preprocessing. A request is not incoming request any more when its proprocessing begins. And after preprocessing, the requests will be put into processing queue.  The value shown in this graph is the minimum number of incoming requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 181 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Minimum Number of Incoming LDLM Canceld Requests",
     "measurement": "ldlm_canceld_stats_req_qdepth_min",
     "query": "SELECT \"value\" FROM \"ldlm_canceld_stats_req_qdepth_min\" WHERE (\"fqdn\" = '$mds') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Average Number of Incoming LDLM Canceld Requests",
   "type": "timeseries",
   "description": "Incoming requests are the requests that waiting on preprocessing. A request is not incoming request any more when its proprocessing begins. And after preprocessing, the requests will be put into processing queue.  The value shown in this graph is the average number of incoming requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 181 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Average Number of Incoming LDLM Canceld Requests",
     "measurement": "ldlm_canceld_stats_req_qdepth_mean",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Maximum Number of Incoming LDLM Canceld Requests",
   "type": "timeseries",
   "description": "Incoming requests are the requests that waiting on preprocessing. A request is not incoming request any more when its proprocessing begins. And after preprocessing, the requests will be put into processing queue.  The value shown in this graph is the maximum number of incoming requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 181 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Maximum Number of Incoming LDLM Canceld Requests",
     "measurement": "ldlm_canceld_stats_req_qdepth_max",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Wait Time of LDLM Canceld Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 189 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Minimum Wait Time of LDLM Canceld Requests",
   "type": "timeseries",
   "description": "The wait time of a request is the time interval between its arrival time and the time when it starts to be handled.  The value shown in this graph is the minimum wait time of the requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 190 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "Minimum Wait Time of LDLM Canceld Requests",
     "measurement": "ldlm_canceld_stats_req_waittime_min",
     "query": "SELECT \"value\" * 1000 FROM \"ldlm_canceld_stats_req_waittime_min\" WHERE (\"fqdn\" = '$mds') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Average Wait Time of LDLM Canceld Requests",
   "type": "timeseries",
   "description": "The wait time of a request is the time interval between its arrival time and the time when it starts to be handled.  The value shown in this graph is the average wait time of the requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 190 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "Average Wait Time of LDLM Canceld Requests",
     "measurement": "ldlm_canceld_stats_req_waittime_min",
     "query": "SELECT \"value\" * 1000 FROM \"ldlm_canceld_stats_req_waittime_mean\" WHERE (\"fqdn\" = '$mds') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Maximum Wait Time of LDLM Canceld Requests",
   "type": "timeseries",
   "description": "The wait time of a request is the time interval between its arrival time and the time when it starts to be handled.  The value shown in this graph is the maximum wait time of the requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 190 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "Maximum Wait Time of LDLM Canceld Requests",
     "measurement": "ldlm_canceld_stats_req_waittime_max",
     "query": "SELECT \"value\" * 1000 FROM \"ldlm_canceld_stats_req_waittime_max\" WHERE (\"fqdn\" = '$mds') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Adaptive Timeout Value of LDLM Canceld Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 198 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Maximum Adaptive Timeout Value of LDLM Canceld  Service",
   "type": "timeseries",
   "description": "When a client sends a request, it has a timeout deadline for the reply. The timeout value of a service is an adaptive value negotiated between server and client during run-time. The value shown in this graph is the maximum timeout of the service during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 199 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "Maximum Adaptive Timeout Value of LDLM Canceld Service",
     "measurement": "ldlm_canceld_stats_req_timeout_max",
     "query": "SELECT \"value\" FROM \"ldlm_canceld_stats_req_timeout_max\" WHERE (\"fqdn\" = '$mds') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Average Adaptive Timeout Value of LDLM Canceld  Service",
   "type": "timeseries",
   "description": "When a client sends a request, it has a timeout deadline for the reply. The timeout value of a service is an adaptive value negotiated between server and client during run-time. The value shown in this graph is the average timeout of the service during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 199 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "Average Adaptive Timeout Value of LDLM Canceld Service",
     "measurement": "ldlm_canceld_stats_req_timeout_mean",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Minimum Adaptive Timeout Value of LDLM Canceld  Service",
   "type": "timeseries",
   "description": "When a client sends a request, it has a timeout deadline for the reply. The timeout value of a service is an adaptive value negotiated between server and client during run-time. The value shown in this graph is the minimum timeout of the service during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 199 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "Minimum Adaptive Timeout Value of LDLM Canceld Service",
     "measurement": "ldlm_canceld_stats_req_timeout_min",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Number of Available LDLM Canceld Request Buffers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 207 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Minimum Number of Available LDLM Canceld Request Buffers",
   "type": "timeseries",
   "description": "When a request arrives, one request buffer will be used. When number of available request buffers is under low water, more buffers are needed to avoid performance bottleneck. The value shown in this graph is the minimum number during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 208 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Minimum Number of Available LDLM Canceld Request Buffers",
     "measurement": "ldlm_canceld_stats_reqbuf_avail_min",
     "query": "SELECT \"value\" FROM \"ldlm_canceld_stats_reqbuf_avail_min\" WHERE (\"fqdn\" = '$mds') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Average Number of Available LDLM Canceld Request Buffers",
   "type": "timeseries",
   "description": "When a request arrives, one request buffer will be used. When number of available request buffers is under low water, more buffers are needed to avoid performance bottleneck. The value shown in this graph is the average number during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 208 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Average Number of Available LDLM Canceld Request Buffers",
     "measurement": "ldlm_canceld_stats_reqbuf_avail_mean",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Maximum Number of Available LDLM Canceld Request Buffers",
   "type": "timeseries",
   "description": "When a request arrives, one request buffer will be used. When number of available request buffers is under low water, more buffers are needed to avoid performance bottleneck. The value shown in this graph is the maximum number during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 208 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Maximum Number of Available LDLM Canceld Request Buffers",
     "measurement": "ldlm_canceld_stats_reqbuf_avail_max",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Number of Active LDLM Callback Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 216 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Minimum Number of Active LDLM Callback Requests",
   "type": "timeseries",
   "description": "Active requests are the requests that is being actively handled, not including the requests that are waiting in the queue.   If the number of active requests is smaller than PTLRPC thread number minus two (one for incoming  request handling and the other for incoming high priority request handling), it generally means the thread number should be enough. The value shown in this graph is the minimum number during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 217 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Minimum Number of Active LDLM Callback Requests",
     "measurement": "ldlm_cbd_stats_req_active_min",
     "query": "SELECT \"value\" FROM \"ldlm_cbd_stats_req_active_min\" WHERE (\"fqdn\" = '$mds') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Average Number of Active LDLM Callback Requests",
   "type": "timeseries",
   "description": "Active requests are the requests that is being actively handled, not including the requests that are waiting in the queue.   If the number of active requests is smaller than PTLRPC thread number minus two (one for incoming  request handling and the other for incoming high priority request handling), it generally means the thread number should be enough. The value shown in this graph is the average number during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 217 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Average Number of Active LDLM Callback Requests",
     "measurement": "ldlm_cbd_stats_req_active_mean",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Maximum Number of Active LDLM Callback Requests",
   "type": "timeseries",
   "description": "Active requests are the requests that is being actively handled, not including the requests that are waiting in the queue.   If the number of active requests is smaller than PTLRPC thread number minus two (one for incoming  request handling and the other for incoming high priority request handling), it generally means the thread number should be enough. The value shown in this graph is the maximum number during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 217 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Maximum Number of Active LDLM Callback Requests",
     "measurement": "ldlm_cbd_stats_req_active_max",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Number of Incoming LDLM Callback Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 225 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Minimum Number of Incoming LDLM Callback Requests",
   "type": "timeseries",
   "description": "Incoming requests are the requests that waiting on preprocessing. A request is not incoming request any more when its proprocessing begins. And after preprocessing, the requests will be put into processing queue.  The value shown in this graph is the minimum number of incoming requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 226 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Minimum Number of Incoming LDLM Callback Requests",
     "measurement": "ldlm_cbd_stats_req_qdepth_min",
     "query": "SELECT \"value\" FROM \"ldlm_cbd_stats_req_qdepth_min\" WHERE (\"fqdn\" = '$mds') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Average Number of Incoming LDLM Callback Requests",
   "type": "timeseries",
   "description": "Incoming requests are the requests that waiting on preprocessing. A request is not incoming request any more when its proprocessing begins. And after preprocessing, the requests will be put into processing queue.  The value shown in this graph is the average number of incoming requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 226 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Average Number of Incoming LDLM Callback Requests",
     "measurement": "ldlm_cbd_stats_req_qdepth_mean",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Maximum Number of Incoming LDLM Callback Requests",
   "type": "timeseries",
   "description": "Incoming requests are the requests that waiting on preprocessing. A request is not incoming request any more when its proprocessing begins. And after preprocessing, the requests will be put into processing queue.  The value shown in this graph is the maximum number of incoming requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 226 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Maximum Number of Incoming LDLM Callback Requests",
     "measurement": "ldlm_cbd_stats_req_qdepth_max",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Wait Time of LDLM Callback Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 234 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Minimum Wait Time of LDLM Callback Requests",
   "type": "timeseries",
   "description": "The wait time of a request is the time interval between its arrival time and the time when it starts to be handled.  The value shown in this graph is the minimum wait time of the requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 235 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "Minimum Wait Time of LDLM Callback Requests",
     "measurement": "ldlm_cbd_stats_req_waittime_min",
     "query": "SELECT \"value\" * 1000 FROM \"ldlm_cbd_stats_req_waittime_min\" WHERE (\"fqdn\" = '$mds') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Average Wait Time of LDLM Callback Requests",
   "type": "timeseries",
   "description": "The wait time of a request is the time interval between its arrival time and the time when it starts to be handled.  The value shown in this graph is the average wait time of the requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 235 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "Average Wait Time of LDLM Callback Requests",
     "measurement": "ldlm_cbd_stats_req_waittime_min",
     "query": "SELECT \"value\" * 1000 FROM \"ldlm_cbd_stats_req_waittime_mean\" WHERE (\"fqdn\" = '$mds') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Maximum Wait Time of LDLM Callback Requests",
   "type": "timeseries",
   "description": "The wait time of a request is the time interval between its arrival time and the time when it starts to be handled.  The value shown in this graph is the maximum wait time of the requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 235 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "Maximum Wait Time of LDLM Callback Requests",
     "measurement": "ldlm_cbd_stats_req_waittime_max",
     "query": "SELECT \"value\" * 1000 FROM \"ldlm_cbd_stats_req_waittime_max\" WHERE (\"fqdn\" = '$mds') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Adaptive Timeout Value of LDLM Callback Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 243 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Minimum Adaptive Timeout Value of LDLM Callback Service",
   "type": "timeseries",
   "description": "When a client sends a request, it has a timeout deadline for the reply. The timeout value of a service is an adaptive value negotiated between server and client during run-time. The value shown in this graph is the minimum timeout of the service during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 244 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "Minimum Adaptive Timeout Value of LDLM Callback Service",
     "measurement": "ldlm_cbd_stats_req_timeout_min",
     "query": "SELECT \"value\" FROM \"ldlm_cbd_stats_req_timeout_min\" WHERE (\"fqdn\" = '$mds') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Average Adaptive Timeout Value of LDLM Callback Service",
   "type": "timeseries",
   "description": "When a client sends a request, it has a timeout deadline for the reply. The timeout value of a service is an adaptive value negotiated between server and client during run-time. The value shown in this graph is the average timeout of the service during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 244 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "Average Adaptive Timeout Value of LDLM Callback Service",
     "measurement": "ldlm_cbd_stats_req_timeout_mean",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Maximum Adaptive Timeout Value of LDLM Callback Service",
   "type": "timeseries",
   "description": "When a client sends a request, it has a timeout deadline for the reply. The timeout value of a service is an adaptive value negotiated between server and client during run-time. The value shown in this graph is the maximum timeout of the service during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 244 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "Maximum Adaptive Timeout Value of LDLM Callback Service",
     "measurement": "ldlm_cbd_stats_req_timeout_max",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Number of Available LDLM Canceld Request Buffers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 252 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Minimum Number of Available LDLM Callback Request Buffers",
   "type": "timeseries",
   "description": "When a request arrives, one request buffer will be used. When number of available request buffers is under low water, more buffers are needed to avoid performance bottleneck. The value shown in this graph is the minimum number during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 253 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Minimum Number of Available LDLM Callback Request Buffers",
     "measurement": "ldlm_cbd_stats_reqbuf_avail_min",
     "query": "SELECT \"value\" FROM \"ldlm_cbd_stats_reqbuf_avail_min\" WHERE (\"fqdn\" = '$mds') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Average Number of Available LDLM Callback Request Buffers",
   "type": "timeseries",
   "description": "When a request arrives, one request buffer will be used. When number of available request buffers is under low water, more buffers are needed to avoid performance bottleneck. The value shown in this graph is the average number during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 253 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Average Number of Available LDLM Callback Request Buffers",
     "measurement": "ldlm_cbd_stats_reqbuf_avail_mean",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  },
  {
   "title": "Maximum Number of Available LDLM Callback Request Buffers",
   "type": "timeseries",
   "description": "When a request arrives, one request buffer will be used. When number of available request buffers is under low water, more buffers are needed to avoid performance bottleneck. The value shown in this graph is the maximum number during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 253 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Maximum Number of Available LDLM Callback Request Buffers",
     "measurement": "ldlm_cbd_stats_reqbuf_avail_max",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$mds" }
     ]
    }
   ]
  }
 ]
}