{
 "title": "Lustre OST",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "fs_name",
    "label": "Filesystem Name",
    "query": "SHOW TAG VALUES FROM \"ost_kbytesinfo_free\" WITH KEY = fs_name"
   },
   {
    "name": "ost_index",
    "label": "OST Index",
    "query": "SHOW TAG VALUES FROM \"ost_kbytesinfo_free\" WITH KEY = ost_index WHERE \"fs_name\" = '$fs_name'"
   },
   { "name": "BARRELEYE_DATASOURCE_NAME", "query": "influxdb" }
  ]
 },
 "panels": [
  {
   "title": "Free Capacity",
   "type": "timeseries",
   "description": "Free capacity on this OST.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "alias": "Free Capacity",
     "groupBy": [
      { "params": [ "optype" ], "type": "tag" }
     ],
     "measurement": "cqm_ost_stats_bytes-optype-fs_name",
     "query": "SELECT \"value\" FROM \"ost_kbytesinfo_free\" WHERE \"fs_name\" = '$fs_name'  AND \"ost_index\" = '$ost_index' AND $timeFilter GROUP BY \"ost_index\"",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" }
     ]
    }
   ]
  },
  {
   "title": "Used Capacity",
   "type": "timeseries",
   "description": "Used capacity on this OST.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "alias": "Used Capacity",
     "groupBy": [
      { "params": [ "optype" ], "type": "tag" }
     ],
     "measurement": "cqm_ost_stats_bytes-optype-fs_name",
     "query": "SELECT \"value\" FROM \"ost_kbytesinfo_used\" WHERE \"fs_name\" = '$fs_name'  AND \"ost_index\" = '$ost_index' AND $timeFilter GROUP BY \"ost_index\"",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" }
     ]
    }
   ]
  },
  {
   "title": "Used Capacity per User",
   "type": "table",
   "description": "The used capacity for each user.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "alias": "UID=$tag_user_id",
     "groupBy": [
      { "params": [ "user_id" ], "type": "tag" }
     ],
     "measurement": "ost_acctuser_samples",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "optype", "operator": "=", "value": "usage_kbytes" },
      { "condition": "AND", "key": "ost_index", "operator": "=", "value": "$ost_index" }
     ]
    }
   ]
  },
  {
   "title": "Used Capacity per Group",
   "type": "table",
   "description": "The used capacity for each group.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "alias": "GID=$tag_group_id",
     "groupBy": [
      { "params": [ "group_id" ], "type": "tag" }
     ],
     "measurement": "ost_acctgroup_samples",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "optype", "operator": "=", "value": "usage_kbytes" },
      { "condition": "AND", "key": "ost_index", "operator": "=", "value": "$ost_index" }
     ]
    }
   ]
  },
  {
   "title": "Used Inode Number per User",
   "type": "table",
   "description": "The used inode number for each user.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "UID=$tag_user_id",
     "groupBy": [
      { "params": [ "user_id" ], "type": "tag" }
     ],
     "measurement": "ost_acctuser_samples",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "optype", "operator": "=", "value": "usage_inodes" },
      { "condition": "AND", "key": "ost_index", "operator": "=", "value": "$ost_index" }
     ]
    }
   ]
  },
  {
   "title": "Used Inode Number per Group",
   "type": "table",
   "description": "The used inode number for each group.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "GID=$tag_group_id",
     "groupBy": [
      { "params": [ "group_id" ], "type": "tag" }
     ],
     "measurement": "ost_acctgroup_samples",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "optype", "operator": "=", "value": "usage_inodes" },
      { "condition": "AND", "key": "ost_index", "operator": "=", "value": "$ost_index" }
     ]
    }
   ]
  },
  {
   "title": "Free Inode Number",
   "type": "timeseries",
   "description": "Free Inode Number on this OST.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Free Inode Number",
     "groupBy": [
      { "params": [ "optype" ], "type": "tag" }
     ],
     "measurement": "cqm_ost_stats_bytes-optype-fs_name",
     "query": "SELECT \"value\" FROM \"ost_filesinfo_free\" WHERE \"fs_name\" = '$fs_name'  AND \"ost_index\" = '$ost_index' AND $timeFilter GROUP BY \"ost_index\"",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" }
     ]
    }
   ]
  },
  {
   "title": "Used Inode Number",
   "type": "timeseries",
   "description": "Used Inode Number on this OST.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Used Inode Number",
     "groupBy": [
      { "params": [ "optype" ], "type": "tag" }
     ],
     "measurement": "cqm_ost_stats_bytes-optype-fs_name",
     "query": "SELECT \"value\" FROM \"ost_filesinfo_used\" WHERE \"fs_name\" = '$fs_name'  AND \"ost_index\" = '$ost_index' AND $timeFilter GROUP BY \"ost_index\"",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" }
     ]
    }
   ]
  },
  {
   "title": "I/O Throughput",
   "type": "timeseries",
   "description": "The I/O throughput on this OST.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "I/O Throughput",
     "measurement": "cqm_ost_stats_bytes-fs_name-ost_index",
     "query": "SELECT \"sum\" FROM \"cqm_ost_stats_bytes-fs_name-ost_index\" WHERE \"fs_name\" = '$fs_name' AND \"optype\" = 'write' AND $timeFilter GROUP BY \"ost_index\"",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "ost_index", "operator": "=", "value": "$ost_index" }
     ]
    }
   ]
  },
  {
   "title": "Write Throughput",
   "type": "timeseries",
   "description": "The write throughput on this OST.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "Write Throughput",
     "measurement": "ost_stats_bytes",
     "query": "SELECT \"sum\" FROM \"cqm_ost_stats_bytes-fs_name-optype-ost_index\" WHERE \"fs_name\" = '$fs_name' AND \"optype\" = 'write' AND $timeFilter GROUP BY \"ost_index\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "ost_index", "operator": "=", "value": "$ost_index" },
      { "condition": "AND", "key": "optype", "operator": "=", "value": "write" }
     ]
    }
   ]
  },
  {
   "title": "Read Throughput",
   "type": "timeseries",
   "description": "The read throughput on this OST.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "Read Throughput",
     "measurement": "ost_stats_bytes",
     "query": "SELECT \"sum\" FROM \"cqm_ost_stats_bytes-fs_name-optype-ost_index\" WHERE \"fs_name\" = '$fs_name' AND \"optype\" = 'write' AND $timeFilter GROUP BY \"ost_index\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "ost_index", "operator": "=", "value": "$ost_index" },
      { "condition": "AND", "key": "optype", "operator": "=", "value": "read" }
     ]
    }
   ]
  },
  {
   "title": "Write Bulk RPC Rate per Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "4k",
     "measurement": "ost_brw_stats_rpc_bulk_samples",
     "query": "SELECT \"value\" FROM \"ost_brw_stats_rpc_bulk_samples\" WHERE \"size\" = '1_pages' AND \"field\" = 'write_sample' AND \"fs_name\" = '$fs_name' AND \"ost_index\" = '$ost_index' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "size", "operator": "=", "value": "1_pages" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "write_sample" },
      { "condition": "AND", "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "ost_index", "operator": "=", "value": "$ost_index" }
     ]
    },
    {
     "alias": "8k",
     "measurement": "ost_brw_stats_rpc_bulk_samples",
     "query": "SELECT \"sum\" FROM \"ost_brw_stats_rpc_bulk_samples\" WHERE \"size\" = '2_pages' AND \"field\" = 'write_sample' AND \"fs_name\" = '$fs_name' AND \"ost_index\" = '$ost_index' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "size", "operator": "=", "value": "2_pages" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "write_sample" },
      { "condition": "AND", "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "ost_index", "operator": "=", "value": "$ost_index" }
     ]
    },
    {
     "alias": "16k",
     "measurement": "ost_brw_stats_rpc_bulk_samples",
     "query": "SELECT \"sum\" FROM \"ost_brw_stats_rpc_bulk_samples\" WHERE \"size\" = '4_pages' AND \"field\" = 'write_sample' AND \"fs_name\" = '$fs_name' AND \"ost_index\" = '$ost_index' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "size", "operator": "=", "value": "4_pages" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "write_sample" },
      { "condition": "AND", "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "ost_index", "operator": "=", "value": "$ost_index" }
     ]
    },
    {
     "alias": "32k",
     "measurement": "ost_brw_stats_rpc_bulk_samples",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "size", "operator": "=", "value": "8_pages" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "write_sample" },
      { "condition": "AND", "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "ost_index", "operator": "=", "value": "$ost_index" }
     ]
    },
    {
     "alias": "64k",
     "measurement": "ost_brw_stats_rpc_bulk_samples",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "size", "operator": "=", "value": "16_pages" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "write_sample" },
      { "condition": "AND", "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "ost_index", "operator": "=", "value": "$ost_index" }
     ]
    },
    {
     "alias": "128k",
     "measurement": "ost_brw_stats_rpc_bulk_samples",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "size", "operator": "=", "value": "32_pages" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "write_sample" },
      { "condition": "AND", "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "ost_index", "operator": "=", "value": "$ost_index" }
     ]
    },
    {
     "alias": "256k",
     "measurement": "ost_brw_stats_rpc_bulk_samples",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "size", "operator": "=", "value": "64_pages" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "write_sample" },
      { "condition": "AND", "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "ost_index", "operator": "=", "value": "$ost_index" }
     ]
    },
    {
     "alias": "512k",
     "measurement": "ost_brw_stats_rpc_bulk_samples",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "size", "operator": "=", "value": "128_pages" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "write_sample" },
      { "condition": "AND", "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "ost_index", "operator": "=", "value": "$ost_index" }
     ]
    },
    {
     "alias": "2m",
     "measurement": "ost_brw_stats_rpc_bulk_samples",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "size", "operator": "=", "value": "512_pages" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "write_sample" },
      { "condition": "AND", "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "ost_index", "operator": "=", "value": "$ost_index" }
     ]
    },
    {
     "alias": "1m",
     "measurement": "ost_brw_stats_rpc_bulk_samples",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "size", "operator": "=", "value": "256_pages" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "write_sample" },
      { "condition": "AND", "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "ost_index", "operator": "=", "value": "$ost_index" }
     ]
    },
    {
     "alias": "4m",
     "measurement": "ost_brw_stats_rpc_bulk_samples",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "size", "operator": "=", "value": "1K_pages" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "write_sample" },
      { "condition": "AND", "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "ost_index", "operator": "=", "value": "$ost_index" }
     ]
    },
    {
     "alias": "8m",
     "measurement": "ost_brw_stats_rpc_bulk_samples",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "size", "operator": "=", "value": "2K_pages" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "write_sample" },
      { "condition": "AND", "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "ost_index", "operator": "=", "value": "$ost_index" }
     ]
    },
    {
     "alias": "16m",
     "measurement": "ost_brw_stats_rpc_bulk_samples",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "size", "operator": "=", "value": "4K_pages" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "write_sample" },
      { "condition": "AND", "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "ost_index", "operator": "=", "value": "$ost_index" }
     ]
    }
   ]
  },
  {
   "title": "Size Distribution of Write Bulk RPC",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_size",
     "groupBy": [
      { "params": [ "size" ], "type": "tag" }
     ],
     "measurement": "ost_brw_stats_rpc_bulk_samples",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "write_sample" },
      { "condition": "AND", "key": "ost_index", "operator": "=", "value": "$ost_index" }
     ]
    }
   ]
  },
  {
   "title": "Read Bulk RPC Rate per Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "4k",
     "measurement": "ost_brw_stats_rpc_bulk_samples",
     "query": "SELECT \"value\" FROM \"ost_brw_stats_rpc_bulk_samples\" WHERE \"size\" = '1_pages' AND \"field\" = 'write_sample' AND \"fs_name\" = '$fs_name' AND \"ost_index\" = '$ost_index' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "size", "operator": "=", "value": "1_pages" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "read_sample" },
      { "condition": "AND", "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "ost_index", "operator": "=", "value": "$ost_index" }
     ]
    },
    {
     "alias": "8k",
     "measurement": "ost_brw_stats_rpc_bulk_samples",
     "query": "SELECT \"sum\" FROM \"ost_brw_stats_rpc_bulk_samples\" WHERE \"size\" = '2_pages' AND \"field\" = 'write_sample' AND \"fs_name\" = '$fs_name' AND \"ost_index\" = '$ost_index' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "size", "operator": "=", "value": "2_pages" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "read_sample" },
      { "condition": "AND", "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "ost_index", "operator": "=", "value": "$ost_index" }
     ]
    },
    {
     "alias": "16k",
     "measurement": "ost_brw_stats_rpc_bulk_samples",
     "query": "SELECT \"sum\" FROM \"ost_brw_stats_rpc_bulk_samples\" WHERE \"size\" = '4_pages' AND \"field\" = 'write_sample' AND \"fs_name\" = '$fs_name' AND \"ost_index\" = '$ost_index' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "size", "operator": "=", "value": "4_pages" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "read_sample" },
      { "condition": "AND", "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "ost_index", "operator": "=", "value": "$ost_index" }
     ]
    },
    {
     "alias": "32k",
     "measurement": "ost_brw_stats_rpc_bulk_samples",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "size", "operator": "=", "value": "8_pages" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "read_sample" },
      { "condition": "AND", "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "ost_index", "operator": "=", "value": "$ost_index" }
     ]
    },
    {
     "alias": "64k",
     "measurement": "ost_brw_stats_rpc_bulk_samples",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "size", "operator": "=", "value": "16_pages" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "read_sample" },
      { "condition": "AND", "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "ost_index", "operator": "=", "value": "$ost_index" }
     ]
    },
    {
     "alias": "128k",
     "measurement": "ost_brw_stats_rpc_bulk_samples",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "size", "operator": "=", "value": "32_pages" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "read_sample" },
      { "condition": "AND", "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "ost_index", "operator": "=", "value": "$ost_index" }
     ]
    },
    {
     "alias": "256k",
     "measurement": "ost_brw_stats_rpc_bulk_samples",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "size", "operator": "=", "value": "64_pages" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "read_sample" },
      { "condition": "AND", "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "ost_index", "operator": "=", "value": "$ost_index" }
     ]
    },
    {
     "alias": "512k",
     "measurement": "ost_brw_stats_rpc_bulk_samples",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "size", "operator": "=", "value": "128_pages" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "read_sample" },
      { "condition": "AND", "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "ost_index", "operator": "=", "value": "$ost_index" }
     ]
    },
    {
     "alias": "2m",
     "measurement": "ost_brw_stats_rpc_bulk_samples",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "size", "operator": "=", "value": "512_pages" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "read_sample" },
      { "condition": "AND", "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "ost_index", "operator": "=", "value": "$ost_index" }
     ]
    },
    {
     "alias": "1m",
     "measurement": "ost_brw_stats_rpc_bulk_samples",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "size", "operator": "=", "value": "256_pages" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "read_sample" },
      { "condition": "AND", "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "ost_index", "operator": "=", "value": "$ost_index" }
     ]
    },
    {
     "alias": "4m",
     "measurement": "ost_brw_stats_rpc_bulk_samples",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "size", "operator": "=", "value": "1K_pages" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "read_sample" },
      { "condition": "AND", "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "ost_index", "operator": "=", "value": "$ost_index" }
     ]
    },
    {
     "alias": "8m",
     "measurement": "ost_brw_stats_rpc_bulk_samples",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "size", "operator": "=", "value": "2K_pages" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "read_sample" },
      { "condition": "AND", "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "ost_index", "operator": "=", "value": "$ost_index" }
     ]
    },
    {
     "alias": "16m",
     "measurement": "ost_brw_stats_rpc_bulk_samples",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "size", "operator": "=", "value": "4K_pages" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "read_sample" },
      { "condition": "AND", "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "ost_index", "operator": "=", "value": "$ost_index" }
     ]
    }
   ]
  },
  {
   "title": "Size Distribution of Read Bulk RPC",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_size",
     "groupBy": [
      { "params": [ "size" ], "type": "tag" }
     ],
     "measurement": "ost_brw_stats_rpc_bulk_samples",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "read_sample" },
      { "condition": "AND", "key": "ost_index", "operator": "=", "value": "$ost_index" }
     ]
    }
   ]
  },
  {
   "title": "Distribution of Discontinuous Pages in Each Write I/O",
   "type": "piechart",
   "description": "If the next page to be written or read in the I/O is not with the next offset, that page is a discontinuous page. There could be multiple discontinuous pages in an I/O. I/Os with less discontinuous pages are more friendly to OSDs.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_size",
     "groupBy": [
      { "params": [ "size" ], "type": "tag" }
     ],
     "measurement": "ost_brw_stats_page_discontiguous_rpc_samples",
     "query": "SELECT \"sum\" FROM \"cqm_ost_brw_stats_page_discontiguous_rpc_samples-field-fs_name-size\" WHERE \"fs_name\" = '$fs_name' AND \"field\" = 'write_sample' AND $timeFilter GROUP BY \"size\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "write_sample" },
      { "condition": "AND", "key": "ost_index", "operator": "=", "value": "$ost_index" }
     ]
    }
   ]
  },
  {
   "title": "Distribution of Discontinuous Pages in Each Read I/O",
   "type": "piechart",
   "description": "If the next page to be written or read in the I/O is not with the next offset, that page is a discontinuous page. There could be multiple discontinuous pages in an I/O. I/Os with less discontinuous pages are more friendly to OSDs.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_size",
     "groupBy": [
      { "params": [ "size" ], "type": "tag" }
     ],
     "measurement": "ost_brw_stats_page_discontiguous_rpc_samples",
     "query": "SELECT \"sum\" FROM \"cqm_ost_brw_stats_page_discontiguous_rpc_samples-field-fs_name-size\" WHERE \"fs_name\" = '$fs_name' AND \"field\" = 'read_sample' AND $timeFilter GROUP BY \"size\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "read_sample" },
      { "condition": "AND", "key": "ost_index", "operator": "=", "value": "$ost_index" }
     ]
    }
   ]
  },
  {
   "title": "Distribution of Discontinuous Blocks in Each Write I/O",
   "type": "piechart",
   "description": "If the next block to be written or read in the I/O is not with the next offset, that block is a discontinuous block. There could be multiple discontinuous block in an I/O. I/Os with less discontinuous blocks are more friendly to OSDs. One page contains multiple blocks. The block size is determined by underline file system (Ldiskfs or ZFS).",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_size",
     "groupBy": [
      { "params": [ "size" ], "type": "tag" }
     ],
     "measurement": "ost_brw_stats_block_discontiguous_rpc_samples",
     "query": "SELECT \"value\" FROM \"ost_brw_stats_block_discontiguous_rpc_samples\" WHERE (\"fs_name\" = '$fs_name' AND \"field\" = 'write_sample' AND \"ost_index\" = '$ost_index') AND $timeFilter GROUP BY \"size\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "write_sample" },
      { "condition": "AND", "key": "ost_index", "operator": "=", "value": "$ost_index" }
     ]
    }
   ]
  },
  {
   "title": "Distribution of Discontinuous Blocks in Each Read I/O",
   "type": "piechart",
   "description": "If the next block to be written or read in the I/O is not with the next offset, that block is a discontinuous block. There could be multiple discontinuous block in an I/O. I/Os with less discontinuous blocks are more friendly to OSDs. One page contains multiple blocks. The block size is determined by underline file system (Ldiskfs or ZFS).",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_size",
     "groupBy": [
      { "params": [ "size" ], "type": "tag" }
     ],
     "measurement": "ost_brw_stats_block_discontiguous_rpc_samples",
     "query": "SELECT \"value\" FROM \"ost_brw_stats_block_discontiguous_rpc_samples\" WHERE (\"fs_name\" = '$fs_name' AND \"field\" = 'read_sample' AND \"ost_index\" = '$ost_index') AND $timeFilter GROUP BY \"size\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "read_sample" },
      { "condition": "AND", "key": "ost_index", "operator": "=", "value": "$ost_index" }
     ]
    }
   ]
  },
  {
   "title": "Distribution of Fragments in Each Write I/O",
   "type": "piechart",
   "description": "Sometimes an I/O is not able to be written/read in a single BIO on OST,  instead, multiple BIOs are submitted. The fragment number of this I/O equals to the BIO number. Usually, less fragments in the I/Os mean better performance.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_size",
     "groupBy": [
      { "params": [ "size" ], "type": "tag" }
     ],
     "measurement": "ost_brw_stats_fragmented_io_samples",
     "query": "SELECT \"sum\" FROM \"cqm_ost_brw_stats_fragmented_io_samples-field-fs_name-size\" WHERE \"fs_name\" = '$fs_name' AND \"field\" = 'write_sample' AND $timeFilter GROUP BY \"size\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "write_sample" },
      { "condition": "AND", "key": "ost_index", "operator": "=", "value": "$ost_index" }
     ]
    }
   ]
  },
  {
   "title": "Distribution of Fragments in Each Read I/O",
   "type": "piechart",
   "description": "Sometimes an I/O is not able to be written/read in a single BIO on OST,  instead, multiple BIOs are submitted. The fragment number of this I/O equals to the BIO number. Usually, less fragments in the I/Os mean better performance.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_size",
     "groupBy": [
      { "params": [ "size" ], "type": "tag" }
     ],
     "measurement": "ost_brw_stats_fragmented_io_samples",
     "query": "SELECT \"sum\" FROM \"cqm_ost_brw_stats_fragmented_io_samples-field-fs_name-size\" WHERE \"fs_name\" = '$fs_name' AND \"field\" = 'read_sample' AND $timeFilter GROUP BY \"size\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "read_sample" },
      { "condition": "AND", "key": "ost_index", "operator": "=", "value": "$ost_index" }
     ]
    }
   ]
  },
  {
   "title": "Distribution of In-fight Write I/O Number when Starting Each Write I/O",
   "type": "piechart",
   "description": "The in-flight I/O number means the BIO that have started but not ended yet. Thus, when starting a BIO, the in-flight I/O increases. By contrast, when a BIO ends, the in-flight I/O number decreases. And when starting a BIO, the current in-flight I/O number will be collected. More in-flight I/Os means more concurrent I/Os on this OST, and thus heavier load for the OST.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_size",
     "groupBy": [
      { "params": [ "size" ], "type": "tag" }
     ],
     "measurement": "ost_brw_stats_io_in_flight_samples",
     "query": "SELECT \"sum\" FROM \"cqm_ost_brw_stats_io_in_flight_samples-field-fs_name-size\" WHERE \"fs_name\" = '$fs_name' AND \"field\" = 'write_sample' AND $timeFilter GROUP BY \"size\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "write_sample" },
      { "condition": "AND", "key": "ost_index", "operator": "=", "value": "$ost_index" }
     ]
    }
   ]
  },
  {
   "title": "Distribution of In-fight Read I/O Number when Starting Each Read I/O",
   "type": "piechart",
   "description": "The in-flight I/O number means the BIO that have started but not ended yet. Thus, when starting a BIO, the in-flight I/O increases. By contrast, when a BIO ends, the in-flight I/O number decreases. And when starting a BIO, the current in-flight I/O number will be collected. More in-flight I/Os means more concurrent I/Os on this OST, and thus heavier load for the OST.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_size",
     "groupBy": [
      { "params": [ "size" ], "type": "tag" }
     ],
     "measurement": "ost_brw_stats_io_in_flight_samples",
     "query": "SELECT \"sum\" FROM \"cqm_ost_brw_stats_io_in_flight_samples-field-fs_name-size\" WHERE \"fs_name\" = '$fs_name' AND \"field\" = 'read_sample' AND $timeFilter GROUP BY \"size\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "read_sample" },
      { "condition": "AND", "key": "ost_index", "operator": "=", "value": "$ost_index" }
     ]
    }
   ]
  },
  {
   "title": "Distribution of Write I/O Time",
   "type": "piechart",
   "description": "The I/O time is the elasped time length between an I/O (Not BIO. A single I/O could sumbit multiple BIOs) starts and ends. Less I/O time of course is better.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_size",
     "groupBy": [
      { "params": [ "size" ], "type": "tag" }
     ],
     "measurement": "ost_brw_stats_io_time_samples",
     "query": "SELECT \"sum\" FROM \"cqm_ost_brw_stats_io_time_samples-field-fs_name-size\" WHERE \"fs_name\" = '$fs_name' AND \"field\" = 'write_sample' AND $timeFilter GROUP BY \"size\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "write_sample" },
      { "condition": "AND", "key": "ost_index", "operator": "=", "value": "$ost_index" }
     ]
    }
   ]
  },
  {
   "title": "Distribution of Read I/O Time",
   "type": "piechart",
   "description": "The I/O time is the elasped time length between an I/O (Not BIO. A single I/O could sumbit multiple BIOs) starts and ends. Less I/O time of course is better.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_size",
     "groupBy": [
      { "params": [ "size" ], "type": "tag" }
     ],
     "measurement": "ost_brw_stats_io_time_samples",
     "query": "SELECT \"sum\" FROM \"cqm_ost_brw_stats_io_time_samples-field-fs_name-size\" WHERE \"fs_name\" = '$fs_name' AND \"field\" = 'read_sample' AND $timeFilter GROUP BY \"size\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "read_sample" },
      { "condition": "AND", "key": "ost_index", "operator": "=", "value": "$ost_index" }
     ]
    }
   ]
  },
  {
   "title": "Distribution of Write I/O Size on Disk",
   "type": "piechart",
   "description": "The I/O size on disk is the size of submitted BIO. Usually, bigger I/O size means better performance.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_size",
     "groupBy": [
      { "params": [ "size" ], "type": "tag" }
     ],
     "measurement": "ost_brw_stats_io_size_samples",
     "query": "SELECT \"sum\" FROM \"cqm_ost_brw_stats_io_size_samples-field-fs_name-size\" WHERE \"fs_name\" = '$fs_name' AND \"field\" = 'write_sample' AND $timeFilter GROUP BY \"size\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "write_sample" },
      { "condition": "AND", "key": "ost_index", "operator": "=", "value": "$ost_index" }
     ]
    }
   ]
  },
  {
   "title": "Distribution of Read I/O Size on Disk",
   "type": "piechart",
   "description": "The I/O size is the size of submitted BIO. Usually, bigger I/O size means better performance.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_size",
     "groupBy": [
      { "params": [ "size" ], "type": "tag" }
     ],
     "measurement": "ost_brw_stats_io_size_samples",
     "query": "SELECT \"sum\" FROM \"cqm_ost_brw_stats_io_size_samples-field-fs_name-size\" WHERE \"fs_name\" = '$fs_name' AND \"field\" = 'read_sample' AND $timeFilter GROUP BY \"size\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "read_sample" },
      { "condition": "AND", "key": "ost_index", "operator": "=", "value": "$ost_index" }
     ]
    }
   ]
  },
  {
   "title": "Write Throughput per Client",
   "type": "table",
   "description": "The write throughput for each client.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "$tag_exp_client",
     "groupBy": [
      { "params": [ "exp_client" ], "type": "tag" }
     ],
     "measurement": "exp_ost_stats_bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "optype", "operator": "=", "value": "write" },
      { "condition": "AND", "key": "ost_index", "operator": "=", "value": "$ost_index" }
     ]
    }
   ]
  },
  {
   "title": "Read Throughput per Client",
   "type": "table",
   "description": "The read throughput for each client.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "$tag_exp_client",
     "groupBy": [
      { "params": [ "exp_client" ], "type": "tag" }
     ],
     "measurement": "exp_ost_stats_bytes",
     "query": "SELECT \"value\" FROM \"exp_ost_stats_bytes\" WHERE (\"fs_name\" = '$fs_name' AND \"optype\" = 'read' AND \"ost_index\" = '$ost_index') AND $timeFilter GROUP BY \"exp_client\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "optype", "operator": "=", "value": "read" },
      { "condition": "AND", "key": "ost_index", "operator": "=", "value": "$ost_index" }
     ]
    }
   ]
  },
  {
   "title": "I/O Throughput per Job",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "targets": [
    {
     "alias": "$tag_job_id",
     "groupBy": [
      { "params": [ "job_id" ], "type": "tag" }
     ],
     "measurement": "cqm_ost_jobstats_bytes-fs_name-job_id-ost_index",
     "query": "SELECT sum(\"sum\") FROM \"cqm_ost_jobstats_bytes\" WHERE ( \"optype\" = 'sum_write_bytes' OR \"optype\" = 'sum_read_bytes' ) AND \"fs_name\" = '$fs_name' AND $timeFilter GROUP BY time(1m), \"job_id\" fill(null)",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "ost_index", "operator": "=", "value": "$ost_index" }
     ]
    }
   ]
  },
  {
   "title": "Write Throughput per Job",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "$tag_job_id",
     "groupBy": [
      { "params": [ "job_id" ], "type": "tag" }
     ],
     "measurement": "ost_jobstats_bytes",
     "query": "SELECT sum(\"sum\") FROM \"cqm_ost_jobstats_bytes\" WHERE \"optype\" = 'sum_write_bytes' AND \"fs_name\" = '$fs_name' AND $timeFilter GROUP BY time(1m), \"job_id\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "optype", "operator": "=", "value": "sum_write_bytes" },
      { "condition": "AND", "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "ost_index", "operator": "=", "value": "$ost_index" }
     ]
    }
   ]
  },
  {
   "title": "Read Throughput per Job",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "$tag_job_id",
     "groupBy": [
      { "params": [ "job_id" ], "type": "tag" }
     ],
     "measurement": "ost_jobstats_bytes",
     "query": "SELECT sum(\"sum\") FROM \"cqm_ost_jobstats_bytes\" WHERE ( \"optype\" = 'sum_write_bytes' OR \"optype\" = 'sum_read_bytes' ) AND \"fs_name\" = '$fs_name' AND $timeFilter GROUP BY time(1m), \"job_id\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "optype", "operator": "=", "value": "sum_read_bytes" },
      { "condition": "AND", "key": "ost_index", "operator": "=", "value": "$ost_index" }
     ]
    }
   ]
  },
  {
   "title": "Metadata Performance per Job",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "alias": "$tag_job_id",
     "groupBy": [
      { "params": [ "job_id" ], "type": "tag" }
     ],
     "measurement": "cqm_mdt_jobstats_samples-fs_name-job_id",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" }
     ]
    }
   ]
  },
  {
   "title": "LDLM Lock Count",
   "type": "timeseries",
   "description": "LDLM lock number allocated on this OST.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "LDLM Lock Count",
     "measurement": "ost_lock_count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "ost_index", "operator": "=", "value": "$ost_index" }
     ]
    }
   ]
  },
  {
   "title": "LDLM Lock Timeouts",
   "type": "timeseries",
   "description": "Number of times this OST evicted clients due to lack of reply to ASTs.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "LDLM Lock Timeouts",
     "measurement": "ost_lock_timeouts",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "ost_index", "operator": "=", "value": "$ost_index" }
     ]
    }
   ]
  },
  {
   "title": "Number of Recovery Clients",
   "type": "timeseries",
   "description": "When Lustre OST/MDT service re-mounted, a recovery process will be started to recover the connections to the clients.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_optype",
     "groupBy": [
      { "params": [ "optype" ], "type": "tag" }
     ],
     "measurement": "ost_recovery_status",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "ost_index", "operator": "=", "value": "$ost_index" }
     ]
    }
   ]
  }
 ]
}