{
 "title": "Lustre OSS",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "fs_name",
    "label": "Filesystem Name",
    "query": "SHOW TAG VALUES FROM \"ost_kbytesinfo_free\" WITH KEY = fs_name"
   },
   {
    "name": "oss",
    "label": "OSS",
    "query": "SHOW TAG VALUES FROM \"ost_kbytesinfo_free\" WITH KEY = fqdn WHERE \"fs_name\" = '$fs_name'"
   },
   { "name": "BARRELEYE_DATASOURCE_NAME", "query": "influxdb" }
  ]
 },
 "panels": [
  {
   "title": "I/O Bandwith",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "I/O Throughput",
   "type": "timeseries",
   "description": "The I/O throughput on this OSS.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "I/O Throughput",
     "measurement": "cqm_ost_stats_bytes-fqdn-fs_name",
     "query": "SELECT \"sum\" FROM \"cqm_ost_stats_bytes-fs_name-ost_index\" WHERE \"fs_name\" = '$fs_name' AND \"optype\" = 'write' AND $timeFilter GROUP BY \"ost_index\"",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Write Throughput",
   "type": "timeseries",
   "description": "The write throughput on this OSS.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "Write Throughput",
     "measurement": "cqm_ost_stats_bytes-fqdn-fs_name-optype",
     "query": "SELECT \"sum\" FROM \"cqm_ost_stats_bytes-fs_name-optype-ost_index\" WHERE \"fs_name\" = '$fs_name' AND \"optype\" = 'write' AND $timeFilter GROUP BY \"ost_index\"",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "optype", "operator": "=", "value": "write" },
      { "condition": "AND", "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Read Throughput",
   "type": "timeseries",
   "description": "The read throughput on this OSS.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "Read Throughput",
     "measurement": "cqm_ost_stats_bytes-fqdn-fs_name-optype",
     "query": "SELECT \"sum\" FROM \"cqm_ost_stats_bytes-fs_name-optype-ost_index\" WHERE \"fs_name\" = '$fs_name' AND \"optype\" = 'write' AND $timeFilter GROUP BY \"ost_index\"",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fs_name", "operator": "=", "value": "$fs_name" },
      { "condition": "AND", "key": "optype", "operator": "=", "value": "read" },
      { "condition": "AND", "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Number of Active Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Minimum Number of Active Requests",
   "type": "timeseries",
   "description": "Active requests are the requests that is being actively handled by  OSS, not including the requests that are waiting in the queue.  If the number of active requests is smaller than PTLRPC thread number minus two (one for incoming  request handling and the other for incoming high priority request handling), it generally means the thread number should be enough. The value shown in this graph is the minimum number during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Minimum Number of Active Requests",
     "measurement": "ost_stats_req_active_min",
     "query": "SELECT \"value\" FROM \"ost_stats_req_active_min\" WHERE (\"fqdn\" = '$oss') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Average Number of Active Requests",
   "type": "timeseries",
   "description": "Active requests are the requests that is being actively handled by  OSS, not including the requests that are waiting in the queue.  If the number of active requests is smaller than PTLRPC thread number minus two (one for incoming  request handling and the other for incoming high priority request handling), it generally means the thread number should be enough. The value shown in this graph is the average number during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Average Number of Active Requests",
     "measurement": "ost_stats_req_active_mean",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Maximum Number of Active Requests",
   "type": "timeseries",
   "description": "Active requests are the requests that is being actively handled by  OSS, not including the requests that are waiting in the queue. If the number of active requests is smaller than PTLRPC thread number minus two (one for incoming  request handling and the other for incoming high priority request handling), it generally means the thread number should be enough. The value shown in this graph is the maximum number during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Maximum Number of Active Requests",
     "measurement": "ost_stats_req_active_max",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Number of Incoming Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Minimum Number of Incoming Requests",
   "type": "timeseries",
   "description": "Incoming requests are the requests that waiting on preprocessing. A request is not incoming request any more when its proprocessing begins. And after preprocessing, the requests will be put into processing queue.  The value shown in this graph is the minimum number of incoming requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Minimum Number of Incoming Requests",
     "measurement": "ost_stats_req_qdepth_min",
     "query": "SELECT \"value\" FROM \"ost_stats_req_qdepth_min\" WHERE (\"fqdn\" = '$oss') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Average Number of Incoming Requests",
   "type": "timeseries",
   "description": "Incoming requests are the requests that waiting on preprocessing. A request is not incoming request any more when its proprocessing begins. And after preprocessing, the requests will be put into processing queue.  The value shown in this graph is the average number of incoming requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Average Number of Incoming Requests",
     "measurement": "ost_stats_req_qdepth_mean",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Maximum Number of Incoming Requests",
   "type": "timeseries",
   "description": "Incoming requests are the requests that waiting on preprocessing. A request is not incoming request any more when its proprocessing begins. And after preprocessing, the requests will be put into processing queue.  The value shown in this graph is the maximum number of incoming requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Maximum Number of Incoming Requests",
     "measurement": "ost_stats_req_qdepth_max",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Wait Time of Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Minimum Wait Time of Requests",
   "type": "timeseries",
   "description": "The wait time of a request is the time interval between its arrival time and the time when it starts to be handled. The value shown in this graph is the maximum wait time of the requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "Minimum Wait Time of Requests",
     "measurement": "ost_stats_req_waittime_min",
     "query": "SELECT \"value\" * 1000 FROM \"ost_stats_req_waittime_min\" WHERE (\"fqdn\" = '$oss') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Average Wait Time of Requests",
   "type": "timeseries",
   "description": "The wait time of a request is the time interval between its arrival time and the time when it starts to be handled. The value shown in this graph is the average wait time of the requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "Average Wait Time of Requests",
     "measurement": "ost_stats_req_waittime_min",
     "query": "SELECT \"value\" * 1000 FROM \"ost_stats_req_waittime_mean\" WHERE (\"fqdn\" = '$oss') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Maximum Wait Time of Requests",
   "type": "timeseries",
   "description": "The wait time of a request is the time interval between its arrival time and the time when it starts to be handled. The value shown in this graph is the maximum wait time of the requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "Maximum Wait Time of Requests",
     "measurement": "ost_stats_req_waittime_max",
     "query": "SELECT \"value\" * 1000 FROM \"ost_stats_req_waittime_max\" WHERE (\"fqdn\" = '$oss') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Adaptive Timeout Value",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Minimum Adaptive Timeout Value",
   "type": "timeseries",
   "description": "When a client sends a request, it has a timeout deadline for the reply. The timeout value of a service is an adaptive value negotiated between server and client during run-time. The value shown in this graph is the minimum timeout of the OST service during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "Minimum Adaptive Timeout Value",
     "measurement": "ost_stats_req_timeout_min",
     "query": "SELECT \"value\" FROM \"ost_stats_req_timeout_min\" WHERE (\"fqdn\" = '$oss') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Average Adaptive Timeout Value",
   "type": "timeseries",
   "description": "When a client sends a request, it has a timeout deadline for the reply. The timeout value of a service is an adaptive value negotiated between server and client during run-time. The value shown in this graph is the average timeout of the OST service during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "Average Adaptive Timeout Value",
     "measurement": "ost_stats_req_timeout_mean",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Maximum Adaptive Timeout Value",
   "type": "timeseries",
   "description": "When a client sends a request, it has a timeout deadline for the reply. The timeout value of a service is an adaptive value negotiated between server and client during run-time. The value shown in this graph is the maximum timeout of the OST service during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "Maximum Adaptive Timeout Value",
     "measurement": "ost_stats_req_timeout_max",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Number of Available Request Buffers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Minimum Number of Available Request Buffers",
   "type": "timeseries",
   "description": "When a request arrives, one request buffer will be used. When number of available request buffers is under low water, more buffers are needed to avoid performance bottleneck. The value shown in this graph is the minimum number during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Minimum Number of Available Request Buffers",
     "measurement": "ost_stats_reqbuf_avail_min",
     "query": "SELECT \"value\" FROM \"ost_stats_reqbuf_avail_min\" WHERE (\"fqdn\" = '$oss') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Average Number of Available Request Buffers",
   "type": "timeseries",
   "description": "When a request arrives, one request buffer will be used. When number of available request buffers is under low water, more buffers are needed to avoid performance bottleneck. The value shown in this graph is the average number during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Average Number of Available Request Buffers",
     "measurement": "ost_stats_reqbuf_avail_mean",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Maximum Number of Available Request Buffers",
   "type": "timeseries",
   "description": "When a request arrives, one request buffer will be used. When number of available request buffers is under low water, more buffers are needed to avoid performance bottleneck. The value shown in this graph is the maximum number during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Maximum Number of Available Request Buffers",
     "measurement": "ost_stats_reqbuf_avail_max",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Number of Active I/O Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Minimum Number of Active Requests",
   "type": "timeseries",
   "description": "Active requests are the requests that is being actively handled by  OSS, not including the requests that are waiting in the queue.   If the number of active requests is smaller than PTLRPC thread number minus two (one for incoming  request handling and the other for incoming high priority request handling), it generally means the thread number should be enough. The value shown in this graph is the minimum number during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Minimum Number of Active I/O Requests",
     "measurement": "ost_io_stats_req_active_min",
     "query": "SELECT \"value\" FROM \"ost_io_stats_req_active_min\" WHERE (\"fqdn\" = '$oss') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Average Number of Active Requests",
   "type": "timeseries",
   "description": "Active requests are the requests that is being actively handled by  OSS, not including the requests that are waiting in the queue.   If the number of active requests is smaller than PTLRPC thread number minus two (one for incoming  request handling and the other for incoming high priority request handling), it generally means the thread number should be enough. The value shown in this graph is the average number during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Average Number of Active I/O Requests",
     "measurement": "ost_io_stats_req_active_mean",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Maximum Number of Active I/O Requests",
   "type": "timeseries",
   "description": "Active requests are the requests that is being actively handled by  OSS, not including the requests that are waiting in the queue.   If the number of active requests is smaller than PTLRPC thread number minus two (one for incoming  request handling and the other for incoming high priority request handling), it generally means the thread number should be enough. The value shown in this graph is the maximum number during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Maximum Number of Active I/O Requests",
     "measurement": "ost_io_stats_req_active_max",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Number of Incoming I/O Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Minimum Number of Incoming I/O Requests",
   "type": "timeseries",
   "description": "Incoming requests are the requests that waiting on preprocessing. A request is not incoming request any more when its proprocessing begins. And after preprocessing, the requests will be put into processing queue.  The value shown in this graph is the minimum number of incoming requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Minimum Number of Incoming I/O Requests",
     "measurement": "ost_io_stats_req_qdepth_min",
     "query": "SELECT \"value\" FROM \"ost_io_stats_req_qdepth_min\" WHERE (\"fqdn\" = '$oss') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Average Number of Incoming I/O Requests",
   "type": "timeseries",
   "description": "Incoming requests are the requests that waiting on preprocessing. A request is not incoming request any more when its proprocessing begins. And after preprocessing, the requests will be put into processing queue.  The value shown in this graph is the average number of incoming requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Average Number of Incoming I/O Requests",
     "measurement": "ost_io_stats_req_qdepth_mean",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Maximum Number of Incoming I/O Requests",
   "type": "timeseries",
   "description": "Incoming requests are the requests that waiting on preprocessing. A request is not incoming request any more when its proprocessing begins. And after preprocessing, the requests will be put into processing queue.  The value shown in this graph is the maximum number of incoming requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Maximum Number of Incoming I/O Requests",
     "measurement": "ost_io_stats_req_qdepth_max",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Wait Time of I/O Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Minimum Wait Time of I/O Requests",
   "type": "timeseries",
   "description": "The wait time of a request is the time interval between its arrival time and the time when it starts to be handled.  The value shown in this graph is the maximum wait time of the requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "Minimum Wait Time of  I/O Requests",
     "measurement": "ost_io_stats_req_waittime_min",
     "query": "SELECT \"value\" * 1000 FROM \"ost_io_stats_req_waittime_min\" WHERE (\"fqdn\" = '$oss') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Average Wait Time of I/O Requests",
   "type": "timeseries",
   "description": "The wait time of a request is the time interval between its arrival time and the time when it starts to be handled.  The value shown in this graph is the average wait time of the requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "Average Wait Time of  I/O Requests",
     "measurement": "ost_io_stats_req_waittime_min",
     "query": "SELECT \"value\" * 1000 FROM \"ost_io_stats_req_waittime_mean\" WHERE (\"fqdn\" = '$oss') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Maximum Wait Time of I/O Requests",
   "type": "timeseries",
   "description": "The wait time of a request is the time interval between its arrival time and the time when it starts to be handled.  The value shown in this graph is the maximum wait time of the requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "Maximum Wait Time of  I/O Requests",
     "measurement": "ost_io_stats_req_waittime_max",
     "query": "SELECT \"value\" * 1000 FROM \"ost_io_stats_req_waittime_max\" WHERE (\"fqdn\" = '$oss') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Adaptive Timeout Value of I/O Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Minimum Adaptive Timeout Value of I/O Service",
   "type": "timeseries",
   "description": "When a client sends a request, it has a timeout deadline for the reply. The timeout value of a service is an adaptive value negotiated between server and client during run-time. The value shown in this graph is the minimum timeout of the OST service during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "Minimum Adaptive Timeout Value of I/O Service",
     "measurement": "ost_io_stats_req_timeout_min",
     "query": "SELECT \"value\" FROM \"ost_io_stats_req_timeout_min\" WHERE (\"fqdn\" = '$oss') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Average Adaptive Timeout Value of I/O Service",
   "type": "timeseries",
   "description": "When a client sends a request, it has a timeout deadline for the reply. The timeout value of a service is an adaptive value negotiated between server and client during run-time. The value shown in this graph is the average timeout of the OST service during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "Average Adaptive Timeout Value of I/O Service",
     "measurement": "ost_io_stats_req_timeout_mean",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Maximum Adaptive Timeout Value of I/O Service",
   "type": "timeseries",
   "description": "When a client sends a request, it has a timeout deadline for the reply. The timeout value of a service is an adaptive value negotiated between server and client during run-time. The value shown in this graph is the maximum timeout of the OST service during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "Maximum Adaptive Timeout Value of I/O Service",
     "measurement": "ost_io_stats_req_timeout_max",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Number of Available I/O Request Buffers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Minimum Number of Available I/O Request Buffers",
   "type": "timeseries",
   "description": "When a request arrives, one request buffer will be used. When number of available request buffers is under low water, more buffers are needed to avoid performance bottleneck. The value shown in this graph is the minimum number during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Minimum Number of Available I/O Request Buffers",
     "measurement": "ost_io_stats_reqbuf_avail_min",
     "query": "SELECT \"value\" FROM \"ost_io_stats_reqbuf_avail_min\" WHERE (\"fqdn\" = '$oss') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Average Number of Available I/O Request Buffers",
   "type": "timeseries",
   "description": "When a request arrives, one request buffer will be used. When number of available request buffers is under low water, more buffers are needed to avoid performance bottleneck. The value shown in this graph is the average number during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Average Number of Available I/O Request Buffers",
     "measurement": "ost_io_stats_reqbuf_avail_mean",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Maximum Number of Available I/O Request Buffers",
   "type": "timeseries",
   "description": "When a request arrives, one request buffer will be used. When number of available request buffers is under low water, more buffers are needed to avoid performance bottleneck. The value shown in this graph is the maximum number during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Maximum Number of Available I/O Request Buffers",
     "measurement": "ost_io_stats_reqbuf_avail_max",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Handling Time of Punch Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 99 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Minimum Handing Time of Punch Requests",
   "type": "timeseries",
   "description": "The handling time of a request is the time interval between the time that it is started to be handled time and the time the handling finishes.  The value shown in this graph is the minimum handling time of the punch requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "Minimum Handing Time of Punch Requests",
     "measurement": "ost_io_stats_ost_punch_min",
     "query": "SELECT \"value\" * 1000 FROM \"ost_io_stats_ost_punch_min\" WHERE (\"fqdn\" = '$oss') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Average Handing Time of Punch Requests",
   "type": "timeseries",
   "description": "The handling time of a request is the time interval between the time that it is started to be handled time and the time the handling finishes.  The value shown in this graph is the average handling time of the punch requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "Average Handing Time of Punch Requests",
     "measurement": "ost_io_stats_ost_punch_min",
     "query": "SELECT \"value\" * 1000 FROM \"ost_io_stats_ost_punch_mean\" WHERE (\"fqdn\" = '$oss') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Maximum Handing Time of Punch Requests",
   "type": "timeseries",
   "description": "The handling time of a request is the time interval between the time that it is started to be handled time and the time the handling finishes.  The value shown in this graph is the maximum handling time of the punch requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "Maximum Handing Time of Punch Requests",
     "measurement": "ost_io_stats_ost_punch_max",
     "query": "SELECT \"value\" * 1000 FROM \"ost_io_stats_ost_punch_max\" WHERE (\"fqdn\" = '$oss') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Handling Time of Read Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 108 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Minimum Handing Time of Read Requests",
   "type": "timeseries",
   "description": "The handling time of a request is the time interval between the time that it is started to be handled time and the time the handling finishes.  The value shown in this graph is the minimum handling time of the read requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "Minimum Handing Time of Read Requests",
     "measurement": "ost_io_stats_ost_read_min",
     "query": "SELECT \"value\" * 1000 FROM \"ost_io_stats_ost_read_min\" WHERE (\"fqdn\" = '$oss') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Average Handing Time of Read Requests",
   "type": "timeseries",
   "description": "The handling time of a request is the time interval between the time that it is started to be handled time and the time the handling finishes.  The value shown in this graph is the average handling time of the read requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "Average Handing Time of Read Requests",
     "measurement": "ost_io_stats_ost_read_min",
     "query": "SELECT \"value\" * 1000 FROM \"ost_io_stats_ost_read_mean\" WHERE (\"fqdn\" = '$oss') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Maximum Handing Time of Read Requests",
   "type": "timeseries",
   "description": "The handling time of a request is the time interval between the time that it is started to be handled time and the time the handling finishes.  The value shown in this graph is the maximum handling time of the read requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "Maximum Handing Time of Read Requests",
     "measurement": "ost_io_stats_ost_read_max",
     "query": "SELECT \"value\" * 1000 FROM \"ost_io_stats_ost_read_max\" WHERE (\"fqdn\" = '$oss') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Handling Time of Write Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 117 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Minimum Handing Time of Write Requests",
   "type": "timeseries",
   "description": "The handling time of a request is the time interval between the time that it is started to be handled time and the time the handling finishes.  The value shown in this graph is the minimum handling time of the write requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "Minimum Handing Time of Write Requests",
     "measurement": "ost_io_stats_ost_write_min",
     "query": "SELECT \"value\" * 1000 FROM \"ost_io_stats_ost_write_min\" WHERE (\"fqdn\" = '$oss') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Average Handing Time of Write Requests",
   "type": "timeseries",
   "description": "The handling time of a request is the time interval between the time that it is started to be handled time and the time the handling finishes.  The value shown in this graph is the average handling time of the write requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "Average Handing Time of Write Requests",
     "measurement": "ost_io_stats_ost_write_min",
     "query": "SELECT \"value\" * 1000 FROM \"ost_io_stats_ost_write_mean\" WHERE (\"fqdn\" = '$oss') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Maximum Handing Time of Write Requests",
   "type": "timeseries",
   "description": "The handling time of a request is the time interval between the time that it is started to be handled time and the time the handling finishes.  The value shown in this graph is the maximum handling time of the write requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "Maximum Handing Time of Write Requests",
     "measurement": "ost_io_stats_ost_write_max",
     "query": "SELECT \"value\" * 1000 FROM \"ost_io_stats_ost_write_max\" WHERE (\"fqdn\" = '$oss') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Number of Active Create Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 126 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Minimum Number of Active Create Requests",
   "type": "timeseries",
   "description": "Active requests are the requests that is being actively handled by OSS, not including the requests that are waiting in the queue.   If the number of active requests is smaller than PTLRPC thread number minus two (one for incoming  request handling and the other for incoming high priority request handling), it generally means the thread number should be enough. Create requests include object creation requests and statfs requests. The value shown in this graph is the minimum number during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Minimum Number of Active Create Requests",
     "measurement": "ost_create_stats_req_active_min",
     "query": "SELECT \"value\" FROM \"ost_create_stats_req_active_min\" WHERE (\"fqdn\" = '$oss') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Average Number of Active Create Requests",
   "type": "timeseries",
   "description": "Active requests are the requests that is being actively handled by OSS, not including the requests that are waiting in the queue.   If the number of active requests is smaller than PTLRPC thread number minus two (one for incoming  request handling and the other for incoming high priority request handling), it generally means the thread number should be enough. Create requests include object creation requests and statfs requests. The value shown in this graph is the average number during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Average Number of Active Create Requests",
     "measurement": "ost_create_stats_req_active_mean",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Maximum Number of Active Create Requests",
   "type": "timeseries",
   "description": "Active requests are the requests that is being actively handled by OSS, not including the requests that are waiting in the queue.   If the number of active requests is smaller than PTLRPC thread number minus two (one for incoming  request handling and the other for incoming high priority request handling), it generally means the thread number should be enough. Create requests include object creation requests and statfs requests. The value shown in this graph is the maximum number during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Maximum Number of Active Create Requests",
     "measurement": "ost_create_stats_req_active_max",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Number of Incoming Create Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 135 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Minimum Number of Incoming Create Requests",
   "type": "timeseries",
   "description": "Incoming requests are the requests that waiting on preprocessing. A request is not incoming request any more when its proprocessing begins. And after preprocessing, the requests will be put into processing queue. Create requests include object creation requests and statfs requests. The value shown in this graph is the minimum number of incoming requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 136 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Minimum Number of Incoming  Create Requests",
     "measurement": "ost_create_stats_req_qdepth_min",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Average Number of Incoming Create Requests",
   "type": "timeseries",
   "description": "Incoming requests are the requests that waiting on preprocessing. A request is not incoming request any more when its proprocessing begins. And after preprocessing, the requests will be put into processing queue. Create requests include object creation requests and statfs requests. The value shown in this graph is the average number of incoming requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 136 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Average Number of Incoming  Create Requests",
     "measurement": "ost_create_stats_req_qdepth_mean",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Maximum Number of Incoming Create Requests",
   "type": "timeseries",
   "description": "Incoming requests are the requests that waiting on preprocessing. A request is not incoming request any more when its proprocessing begins. And after preprocessing, the requests will be put into processing queue. Create requests include object creation requests and statfs requests. The value shown in this graph is the maximum number of incoming requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 136 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Maximum Number of Incoming  Create Requests",
     "measurement": "ost_create_stats_req_qdepth_max",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Wait Time of Create Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 144 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Maximum Wait Time of Create Requests",
   "type": "timeseries",
   "description": "The wait time of a request is the time interval between its arrival time and the time when it starts to be handled. Create requests include object creation requests and statfs requests. The value shown in this graph is the maximum wait time of the create requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "Maximum Wait Time of Create Requests",
     "measurement": "ost_create_stats_req_waittime_max",
     "query": "SELECT \"value\" * 1000 FROM \"ost_create_stats_req_waittime_max\" WHERE (\"fqdn\" = '$oss') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Minimum Wait Time of Create Requests",
   "type": "timeseries",
   "description": "The wait time of a request is the time interval between its arrival time and the time when it starts to be handled. Create requests include object creation requests and statfs requests. The value shown in this graph is the maximum wait time of the create requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "Mnimum Wait Time of Create Requests",
     "measurement": "ost_create_stats_req_waittime_min",
     "query": "SELECT \"value\" * 1000 FROM \"ost_create_stats_req_waittime_min\" WHERE (\"fqdn\" = '$oss') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Average Wait Time of Create Requests",
   "type": "timeseries",
   "description": "The wait time of a request is the time interval between its arrival time and the time when it starts to be handled. Create requests include object creation requests and statfs requests. The value shown in this graph is the average wait time of the create requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "Average Wait Time of Create Requests",
     "measurement": "ost_create_stats_req_waittime_min",
     "query": "SELECT \"value\" * 1000 FROM \"ost_create_stats_req_waittime_mean\" WHERE (\"fqdn\" = '$oss') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Adaptive Timeout Value of Create Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 153 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Minimum Adaptive Timeout Value of create Service",
   "type": "timeseries",
   "description": "When a client sends a request, it has a timeout deadline for the reply. The timeout value of a service is an adaptive value negotiated between server and client during run-time. Create requests include object creation requests and statfs requests. The value shown in this graph is the minimum timeout of the OST create service during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 154 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "Minimum Adaptive Timeout Value of Create Service",
     "measurement": "ost_create_stats_req_timeout_min",
     "query": "SELECT \"value\" FROM \"ost_create_stats_req_timeout_min\" WHERE (\"fqdn\" = '$oss') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Average Adaptive Timeout Value of create Service",
   "type": "timeseries",
   "description": "When a client sends a request, it has a timeout deadline for the reply. The timeout value of a service is an adaptive value negotiated between server and client during run-time. Create requests include object creation requests and statfs requests. The value shown in this graph is the average timeout of the OST create service during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 154 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "Average Adaptive Timeout Value of Create Service",
     "measurement": "ost_create_stats_req_timeout_mean",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Maximum Adaptive Timeout Value of create Service",
   "type": "timeseries",
   "description": "When a client sends a request, it has a timeout deadline for the reply. The timeout value of a service is an adaptive value negotiated between server and client during run-time. Create requests include object creation requests and statfs requests. The value shown in this graph is the maximum timeout of the OST create service during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 154 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "Maximum Adaptive Timeout Value of Create Service",
     "measurement": "ost_create_stats_req_timeout_max",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Number of Available Create Request Buffers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 162 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Minimum Number of Available Create Request Buffers",
   "type": "timeseries",
   "description": "When a request arrives, one request buffer will be used. When number of available request buffers is under low water, more buffers are needed to avoid performance bottleneck. Create requests include object creation requests and statfs requests. The value shown in this graph is the minimum number during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 163 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Minimum Number of Available Create Request Buffers",
     "measurement": "ost_create_stats_reqbuf_avail_min",
     "query": "SELECT \"value\" FROM \"ost_create_stats_reqbuf_avail_min\" WHERE (\"fqdn\" = '$oss') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Average Number of Available Create Request Buffers",
   "type": "timeseries",
   "description": "When a request arrives, one request buffer will be used. When number of available request buffers is under low water, more buffers are needed to avoid performance bottleneck. Create requests include object creation requests and statfs requests. The value shown in this graph is the average number during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 163 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Average Number of Available Create Request Buffers",
     "measurement": "ost_create_stats_reqbuf_avail_mean",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Maximum Number of Available Create Request Buffers",
   "type": "timeseries",
   "description": "When a request arrives, one request buffer will be used. When number of available request buffers is under low water, more buffers are needed to avoid performance bottleneck. Create requests include object creation requests and statfs requests. The value shown in this graph is the maximum number during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 163 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Maximum Number of Available Create Request Buffers",
     "measurement": "ost_create_stats_reqbuf_avail_max",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Number of Active LDLM Canceld Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 171 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Minimum Number of Active LDLM Canceld Requests",
   "type": "timeseries",
   "description": "Active requests are the requests that is being actively handled, not including the requests that are waiting in the queue.   If the number of active requests is smaller than PTLRPC thread number minus two (one for incoming  request handling and the other for incoming high priority request handling), it generally means the thread number should be enough. The value shown in this graph is the minimum number during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 172 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Minimum Number of Active LDLM Canceld Requests",
     "measurement": "ldlm_canceld_stats_req_active_min",
     "query": "SELECT \"value\" FROM \"ldlm_canceld_stats_req_active_min\" WHERE (\"fqdn\" = '$oss') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Average Number of Active LDLM Canceld Requests",
   "type": "timeseries",
   "description": "Active requests are the requests that is being actively handled, not including the requests that are waiting in the queue.   If the number of active requests is smaller than PTLRPC thread number minus two (one for incoming  request handling and the other for incoming high priority request handling), it generally means the thread number should be enough. The value shown in this graph is the average number during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 172 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Average Number of Active LDLM Canceld Requests",
     "measurement": "ldlm_canceld_stats_req_active_mean",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Maximum Number of Active LDLM Canceld Requests",
   "type": "timeseries",
   "description": "Active requests are the requests that is being actively handled, not including the requests that are waiting in the queue.   If the number of active requests is smaller than PTLRPC thread number minus two (one for incoming  request handling and the other for incoming high priority request handling), it generally means the thread number should be enough. The value shown in this graph is the maximum number during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 172 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Maximum Number of Active LDLM Canceld Requests",
     "measurement": "ldlm_canceld_stats_req_active_max",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Number of Incoming LDLM Canceld Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 180 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Minimum Number of Incoming LDLM Canceld Requests",
   "type": "timeseries",
   "description": "Incoming requests are the requests that waiting on preprocessing. A request is not incoming request any more when its proprocessing begins. And after preprocessing, the requests will be put into processing queue.  The value shown in this graph is the minimum number of incoming requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 181 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Minimum Number of Incoming LDLM Canceld Requests",
     "measurement": "ldlm_canceld_stats_req_qdepth_min",
     "query": "SELECT \"value\" FROM \"ldlm_canceld_stats_req_qdepth_min\" WHERE (\"fqdn\" = '$oss') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Average Number of Incoming LDLM Canceld Requests",
   "type": "timeseries",
   "description": "Incoming requests are the requests that waiting on preprocessing. A request is not incoming request any more when its proprocessing begins. And after preprocessing, the requests will be put into processing queue.  The value shown in this graph is the average number of incoming requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 181 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Average Number of Incoming LDLM Canceld Requests",
     "measurement": "ldlm_canceld_stats_req_qdepth_mean",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Maximum Number of Incoming LDLM Canceld Requests",
   "type": "timeseries",
   "description": "Incoming requests are the requests that waiting on preprocessing. A request is not incoming request any more when its proprocessing begins. And after preprocessing, the requests will be put into processing queue.  The value shown in this graph is the maximum number of incoming requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 181 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Maximum Number of Incoming LDLM Canceld Requests",
     "measurement": "ldlm_canceld_stats_req_qdepth_max",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Wait Time of LDLM Canceld Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 189 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Minimum Wait Time of LDLM Canceld Requests",
   "type": "timeseries",
   "description": "The wait time of a request is the time interval between its arrival time and the time when it starts to be handled.  The value shown in this graph is the minimum wait time of the requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 190 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "Minimum Wait Time of LDLM Canceld Requests",
     "measurement": "mdt_readpage_stats_req_waittime_min",
     "query": "SELECT \"value\" * 1000 FROM \"ldlm_canceld_stats_req_waittime_min\" WHERE (\"fqdn\" = '$oss') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Average Wait Time of LDLM Canceld Requests",
   "type": "timeseries",
   "description": "The wait time of a request is the time interval between its arrival time and the time when it starts to be handled.  The value shown in this graph is the average wait time of the requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 190 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "Average Wait Time of LDLM Canceld Requests",
     "measurement": "mdt_readpage_stats_req_waittime_min",
     "query": "SELECT \"value\" * 1000 FROM \"ldlm_canceld_stats_req_waittime_mean\" WHERE (\"fqdn\" = '$oss') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Maximum Wait Time of LDLM Canceld Requests",
   "type": "timeseries",
   "description": "The wait time of a request is the time interval between its arrival time and the time when it starts to be handled.  The value shown in this graph is the maximum wait time of the requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 190 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "Maximum Wait Time of LDLM Canceld Requests",
     "measurement": "mdt_readpage_stats_req_waittime",
     "query": "SELECT \"value\" * 1000 FROM \"ldlm_canceld_stats_req_waittime_max\" WHERE (\"fqdn\" = '$oss') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Adaptive Timeout Value of LDLM Canceld Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 198 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Minimum Adaptive Timeout Value of LDLM Canceld  Service",
   "type": "timeseries",
   "description": "When a client sends a request, it has a timeout deadline for the reply. The timeout value of a service is an adaptive value negotiated between server and client during run-time. The value shown in this graph is the minimum timeout of the service during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 199 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "Minimum Adaptive Timeout Value of LDLM Canceld Service",
     "measurement": "ldlm_canceld_stats_req_timeout_min",
     "query": "SELECT \"value\" FROM \"ldlm_canceld_stats_req_timeout_min\" WHERE (\"fqdn\" = '$oss') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Average Adaptive Timeout Value of LDLM Canceld  Service",
   "type": "timeseries",
   "description": "When a client sends a request, it has a timeout deadline for the reply. The timeout value of a service is an adaptive value negotiated between server and client during run-time. The value shown in this graph is the average timeout of the service during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 199 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "Average Adaptive Timeout Value of LDLM Canceld Service",
     "measurement": "ldlm_canceld_stats_req_timeout_mean",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Maximum Adaptive Timeout Value of LDLM Canceld  Service",
   "type": "timeseries",
   "description": "When a client sends a request, it has a timeout deadline for the reply. The timeout value of a service is an adaptive value negotiated between server and client during run-time. The value shown in this graph is the maximum timeout of the service during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 199 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "Maximum Adaptive Timeout Value of LDLM Canceld Service",
     "measurement": "ldlm_canceld_stats_req_timeout_max",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Number of Available LDLM Canceld Request Buffers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 207 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Minimum Number of Available LDLM Canceld Request Buffers",
   "type": "timeseries",
   "description": "When a request arrives, one request buffer will be used. When number of available request buffers is under low water, more buffers are needed to avoid performance bottleneck. The value shown in this graph is the minimum number during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 208 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Minimum Number of Available LDLM Canceld Request Buffers",
     "measurement": "ldlm_canceld_stats_reqbuf_avail_min",
     "query": "SELECT \"value\" FROM \"ldlm_canceld_stats_reqbuf_avail_min\" WHERE (\"fqdn\" = '$oss') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Average Number of Available LDLM Canceld Request Buffers",
   "type": "timeseries",
   "description": "When a request arrives, one request buffer will be used. When number of available request buffers is under low water, more buffers are needed to avoid performance bottleneck. The value shown in this graph is the average number during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 208 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Average Number of Available LDLM Canceld Request Buffers",
     "measurement": "ldlm_canceld_stats_reqbuf_avail_mean",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Maximum Number of Available LDLM Canceld Request Buffers",
   "type": "timeseries",
   "description": "When a request arrives, one request buffer will be used. When number of available request buffers is under low water, more buffers are needed to avoid performance bottleneck. The value shown in this graph is the maximum number during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 208 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Maximum Number of Available LDLM Canceld Request Buffers",
     "measurement": "ldlm_canceld_stats_reqbuf_avail_max",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Number of Active LDLM Callback Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 216 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Minimum Number of Active LDLM Callback Requests",
   "type": "timeseries",
   "description": "Active requests are the requests that is being actively handled, not including the requests that are waiting in the queue.   If the number of active requests is smaller than PTLRPC thread number minus two (one for incoming  request handling and the other for incoming high priority request handling), it generally means the thread number should be enough. The value shown in this graph is the minimum number during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 217 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Minimum Number of Active LDLM Callback Requests",
     "measurement": "ldlm_cbd_stats_req_active_min",
     "query": "SELECT \"value\" FROM \"ldlm_cbd_stats_req_active_min\" WHERE (\"fqdn\" = '$oss') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Average Number of Active LDLM Callback Requests",
   "type": "timeseries",
   "description": "Active requests are the requests that is being actively handled, not including the requests that are waiting in the queue.   If the number of active requests is smaller than PTLRPC thread number minus two (one for incoming  request handling and the other for incoming high priority request handling), it generally means the thread number should be enough. The value shown in this graph is the average number during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 217 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Average Number of Active LDLM Callback Requests",
     "measurement": "ldlm_cbd_stats_req_active_mean",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Maximum Number of Active LDLM Callback Requests",
   "type": "timeseries",
   "description": "Active requests are the requests that is being actively handled, not including the requests that are waiting in the queue.   If the number of active requests is smaller than PTLRPC thread number minus two (one for incoming  request handling and the other for incoming high priority request handling), it generally means the thread number should be enough. The value shown in this graph is the maximum number during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 217 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Maximum Number of Active LDLM Callback Requests",
     "measurement": "ldlm_cbd_stats_req_active_max",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Number of Incoming LDLM Callback Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 225 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Minimum Number of Incoming LDLM Callback Requests",
   "type": "timeseries",
   "description": "Incoming requests are the requests that waiting on preprocessing. A request is not incoming request any more when its proprocessing begins. And after preprocessing, the requests will be put into processing queue.  The value shown in this graph is the minimum number of incoming requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 226 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Minimum Number of Incoming LDLM Callback Requests",
     "measurement": "ldlm_cbd_stats_req_qdepth_min",
     "query": "SELECT \"value\" FROM \"ldlm_cbd_stats_req_qdepth_min\" WHERE (\"fqdn\" = '$oss') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Average Number of Incoming LDLM Callback Requests",
   "type": "timeseries",
   "description": "Incoming requests are the requests that waiting on preprocessing. A request is not incoming request any more when its proprocessing begins. And after preprocessing, the requests will be put into processing queue.  The value shown in this graph is the average number of incoming requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 226 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Average Number of Incoming LDLM Callback Requests",
     "measurement": "ldlm_cbd_stats_req_qdepth_mean",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Maximum Number of Incoming LDLM Callback Requests",
   "type": "timeseries",
   "description": "Incoming requests are the requests that waiting on preprocessing. A request is not incoming request any more when its proprocessing begins. And after preprocessing, the requests will be put into processing queue.  The value shown in this graph is the maximum number of incoming requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 226 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Maximum Number of Incoming LDLM Callback Requests",
     "measurement": "ldlm_cbd_stats_req_qdepth_max",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Wait Time of LDLM Callback Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 234 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Minimum Wait Time of LDLM Callback Requests",
   "type": "timeseries",
   "description": "The wait time of a request is the time interval between its arrival time and the time when it starts to be handled.  The value shown in this graph is the minimum wait time of the requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 235 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "Minimum Wait Time of LDLM Callback Requests",
     "measurement": "mdt_readpage_stats_req_waittime_min",
     "query": "SELECT \"value\" * 1000 FROM \"ldlm_cbd_stats_req_waittime_min\" WHERE (\"fqdn\" = '$oss') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Average Wait Time of LDLM Callback Requests",
   "type": "timeseries",
   "description": "The wait time of a request is the time interval between its arrival time and the time when it starts to be handled.  The value shown in this graph is the average wait time of the requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 235 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "Average Wait Time of LDLM Callback Requests",
     "measurement": "mdt_readpage_stats_req_waittime_min",
     "query": "SELECT \"value\" * 1000 FROM \"ldlm_cbd_stats_req_waittime_mean\" WHERE (\"fqdn\" = '$oss') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Maximum Wait Time of LDLM Callback Requests",
   "type": "timeseries",
   "description": "The wait time of a request is the time interval between its arrival time and the time when it starts to be handled.  The value shown in this graph is the maximum wait time of the requests during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 235 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "Maximum Wait Time of LDLM Callback Requests",
     "measurement": "mdt_readpage_stats_req_waittime_max",
     "query": "SELECT \"value\" * 1000 FROM \"ldlm_cbd_stats_req_waittime_max\" WHERE (\"fqdn\" = '$oss' AND \"type\" = 'max') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Adaptive Timeout Value of LDLM Callback Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 243 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Minimum Adaptive Timeout Value of LDLM Callback Service",
   "type": "timeseries",
   "description": "When a client sends a request, it has a timeout deadline for the reply. The timeout value of a service is an adaptive value negotiated between server and client during run-time. The value shown in this graph is the minimum timeout of the service during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 244 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "Minimum Adaptive Timeout Value of LDLM Callback Service",
     "measurement": "ldlm_cbd_stats_req_timeout_min",
     "query": "SELECT \"value\" FROM \"ldlm_cbd_stats_req_timeout_min\" WHERE (\"fqdn\" = '$oss') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Average Adaptive Timeout Value of LDLM Callback Service",
   "type": "timeseries",
   "description": "When a client sends a request, it has a timeout deadline for the reply. The timeout value of a service is an adaptive value negotiated between server and client during run-time. The value shown in this graph is the average timeout of the service during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 244 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "Average Adaptive Timeout Value of LDLM Callback Service",
     "measurement": "ldlm_cbd_stats_req_timeout_mean",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Maximum Adaptive Timeout Value of LDLM Callback Service",
   "type": "timeseries",
   "description": "When a client sends a request, it has a timeout deadline for the reply. The timeout value of a service is an adaptive value negotiated between server and client during run-time. The value shown in this graph is the maximum timeout of the service during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 244 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "Maximum Adaptive Timeout Value of LDLM Callback Service",
     "measurement": "ldlm_cbd_stats_req_timeout_max",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Number of Available LDLM Canceld Request Buffers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 252 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Minimum Number of Available LDLM Callback Request Buffers",
   "type": "timeseries",
   "description": "When a request arrives, one request buffer will be used. When number of available request buffers is under low water, more buffers are needed to avoid performance bottleneck. The value shown in this graph is the minimum number during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 253 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Minimum Number of Available LDLM Callback Request Buffers",
     "measurement": "ldlm_cbd_stats_reqbuf_avail_min",
     "query": "SELECT \"value\" FROM \"ldlm_cbd_stats_reqbuf_avail_min\" WHERE (\"fqdn\" = '$oss') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Average Number of Available LDLM Callback Request Buffers",
   "type": "timeseries",
   "description": "When a request arrives, one request buffer will be used. When number of available request buffers is under low water, more buffers are needed to avoid performance bottleneck. The value shown in this graph is the average number during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 253 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Average Number of Available LDLM Callback Request Buffers",
     "measurement": "ldlm_cbd_stats_reqbuf_avail_mean",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  },
  {
   "title": "Maximum Number of Available LDLM Callback Request Buffers",
   "type": "timeseries",
   "description": "When a request arrives, one request buffer will be used. When number of available request buffers is under low water, more buffers are needed to avoid performance bottleneck. The value shown in this graph is the maximum number during the last collect interval.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 253 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Maximum Number of Available LDLM Callback Request Buffers",
     "measurement": "ldlm_cbd_stats_reqbuf_avail_max",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$oss" }
     ]
    }
   ]
  }
 ]
}