{
 "title": "Server Statistics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "fqdn",
    "label": "Server Host Name",
    "query": "SHOW TAG VALUES FROM \"memory.buffered.memory\" WITH KEY = fqdn"
   },
   { "name": "BARRELEYE_DATASOURCE_NAME", "query": "influxdb" }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "######  &emsp; The amount of time spent by the CPU in various states, most notably executing user code, executing system code, waiting for IO-operations and being idle.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Idle",
     "measurement": "aggregation.cpu-average.cpu.idle",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$fqdn" }
     ]
    },
    {
     "alias": "Interrupt",
     "measurement": "aggregation.cpu-average.cpu.interrupt",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$fqdn" }
     ]
    },
    {
     "alias": "Nice",
     "measurement": "aggregation.cpu-average.cpu.nice",
     "query": "SELECT \"value\" FROM \"aggregation.cpu-average.cpu.nice\" WHERE \"fqdn\" = '$fqdn' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$fqdn" }
     ]
    },
    {
     "alias": "Softirq",
     "measurement": "aggregation.cpu-average.cpu.softirq",
     "query": "SELECT \"value\" FROM \"aggregation.cpu-average.cpu.softirq\" WHERE \"fqdn\" = '$fqdn' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$fqdn" }
     ]
    },
    {
     "alias": "Steal",
     "measurement": "aggregation.cpu-average.cpu.steal",
     "query": "SELECT \"value\" FROM \"aggregation.cpu-average.cpu.steal\" WHERE \"fqdn\" = '$fqdn' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "System",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"value\" FROM \"aggregation.cpu-average.cpu.system\" WHERE \"fqdn\" = '$fqdn' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "User",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"value\" FROM \"aggregation.cpu-average.cpu.user\" WHERE \"fqdn\" = '$fqdn' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Wait",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"value\" FROM \"aggregation.cpu-average.cpu.wait\" WHERE \"fqdn\" = '$fqdn' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "General Status",
   "type": "grafana-polystat-panel",
   "description": "#### _Warning(yellow)_\n###### &emsp; if one or more of the following conditions are true:\n  * Idle CPU is less than 20%.\n  * Load is higher than 5\n  * Free memory is less than 1000 MiB;\n  * Free space of \"/\" is less than 10 GiB;\n#### _Critial(red)_\n ###### &emsp; if one or more of the following conditions are true:\n  + Idle CPU is less than 5%.\n  + Load is higher than 10\n  + Free space of \"/\" is less than 1 GiB;\n  + Free memory is less than 100 MiB;\n\n----\n######   &emsp; The system load is defined as the number of runnable tasks in the run-queue and is provided by many operating systems as a one minute average.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "Idle CPU (%)",
     "crit": 5,
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "measurement": "df.root.df_complex.free",
     "query": "\n\nSELECT last(\"value\") FROM \"aggregation.cpu-average.cpu.idle\" WHERE \"fqdn\" = '$fqdn' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1073844224" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$fqdn" }
     ],
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 20
    },
    {
     "aggregation": "Last",
     "alias": "Load",
     "crit": 10,
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"value\") FROM \"load.load.shortterm\" WHERE \"fqdn\" = '$fqdn' AND $timeFilter\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 5
    },
    {
     "aggregation": "Last",
     "alias": "Free Memory (MiB)",
     "crit": 100,
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "measurement": "aggregation.cpu-average.cpu.idle",
     "query": "SELECT last(\"value\")  / 1048576 FROM \"memory.free.memory\" WHERE \"fqdn\" = '$fqdn' AND $timeFilter\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$fqdn" }
     ],
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 1000
    },
    {
     "aggregation": "Last",
     "alias": "Free Space on Root (GiB)",
     "crit": 1,
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "measurement": "load.load.shortterm",
     "query": "SELECT last(\"value\")  / 1073844224 FROM \"df.root.df_complex.free\" WHERE \"fqdn\" = '$fqdn' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$fqdn" }
     ],
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 10
    },
    {
     "aggregation": "Last",
     "alias": "Max Temperature(°C)",
     "crit": 80,
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "measurement": "aggregation.sensors-max.temperature",
     "query": "SELECT last(\"value\") FROM \"aggregation.sensors-max.temperature\" WHERE \"fqdn\" = '$fqdn' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$fqdn" }
     ],
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 60
    },
    {
     "aggregation": "Last",
     "alias": "Uptime (Days)",
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"value\") / 86928   FROM \"uptime.uptime\" WHERE \"fqdn\" = '$fqdn' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "valueHandler": "String Threshold"
    },
    {
     "aggregation": "Last",
     "alias": "Users",
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "measurement": "users.users",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$fqdn" }
     ],
     "valueHandler": "String Threshold"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "###### &emsp; The values are reported by the operating system.  The categories are: \n - Used \n - Buffered \n - Cached \n - Free\n - Slab recl\n - Slab unrecl \n\n----\n###### &emsp; _Free memory_ is memory you paid for, that's using power and that doesn't do anything useful. It is normal that the operating system puts that memory to use.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "Used",
     "measurement": "memory.used.memory",
     "query": "SELECT sum(\"value\") FROM \"aggregation.cpu-average.cpu.system\" WHERE $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$fqdn" }
     ]
    },
    {
     "alias": "Buffered",
     "measurement": "memory.buffered.memory",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$fqdn" }
     ]
    },
    {
     "alias": "Cached",
     "measurement": "memory.cached.memory",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$fqdn" }
     ]
    },
    {
     "alias": "Free",
     "measurement": "memory.free.memory",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$fqdn" }
     ]
    },
    {
     "alias": "Slab_recl",
     "measurement": "memory.slab_recl.memory",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$fqdn" }
     ]
    },
    {
     "alias": "Slab_unrecl",
     "measurement": "memory.slab_unrecl.memory",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$fqdn" }
     ]
    }
   ]
  },
  {
   "title": "Disk Write Rate",
   "type": "timeseries",
   "description": "###### &emsp; This panel shows the writting rate for each disk.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk.sda.disk_octets.read",
     "query": "SELECT \"value\" FROM /disk\\..*\\.disk_octets.write/ WHERE \"fqdn\" = '$fqdn' AND $timeFilter\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk Read Rate",
   "type": "timeseries",
   "description": "###### &emsp; This panel shows the reading rate for each disk.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"value\" FROM /disk\\..*\\.disk_octets.read/ WHERE \"fqdn\" = '$fqdn' AND $timeFilter\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk Usage on Root",
   "type": "timeseries",
   "description": "###### &emsp; This value show the usage of the disk which is mounted as Root. There will be three categories:\n - Free\n - Used\n - Reserved\n\n----\n###### _Warning_ will be reported when there's a little free space left.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "Reserved",
     "measurement": "df.root.df_complex.reserved",
     "query": "SELECT \"value\"   FROM \"df.root.df_complex.free\" WHERE \"fqdn\" = '$fqdn' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$fqdn" }
     ]
    },
    {
     "alias": "Free",
     "measurement": "df.root.df_complex.free",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$fqdn" }
     ]
    },
    {
     "alias": "Used",
     "measurement": "df.root.df_complex.used",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$fqdn" }
     ]
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "description": "###### &emsp; The system load is defined as the number of runnable tasks in the run-queue and is provided by many operating systems as:\n  - Shortterm --- one minute average\n  - Midterm ---  five minutes average\n  - Longterm --- fifteen minutes average",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Longterm",
     "measurement": "load.load.longterm",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Midterm",
     "measurement": "load.load.midterm",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Shortterm",
     "measurement": "load.load.shortterm",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "timeseries",
   "description": "###### &emsp; It keeps track of the system uptime, providing informations such as the average running time or the maximum reached uptime over a certain period of time",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "Uptime",
     "measurement": "uptime.uptime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$fqdn" }
     ]
    }
   ]
  },
  {
   "title": "Users",
   "type": "timeseries",
   "description": "###### &emsp; Counts the The number of users currently logged into the system.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Users",
     "measurement": "users.users",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$fqdn" }
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "description": "###### &emsp; System Temperature is collected by sensors. This panel shows the temperture of these sensors.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "\nSELECT \"value\" FROM /sensors\\..*\\.temperature\\..*/  WHERE \"fqdn\" = '$fqdn' AND $timeFilter\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}