{
 "title": "SFA Physical Disk",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "fqdn",
    "label": "SFA Name",
    "query": "SHOW TAG VALUES FROM \"pd_iosize\" WITH KEY = fqdn"
   },
   {
    "name": "disk_index",
    "label": "Disk Index",
    "query": "SHOW TAG VALUES FROM \"pd_iosize\" WITH KEY = disk_index"
   },
   {
    "name": "BARRELEYE_COLLECT_INTERVAL",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "BARRELEYE_DATASOURCE_NAME", "query": "influxdb" }
  ]
 },
 "panels": [
  {
   "title": "I/O Performance on Physical Disk \"$disk_index\" of SFA \"$fqdn\"",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "alias": "Controller $tag_controller",
     "groupBy": [
      { "params": [ "controller" ], "type": "tag" }
     ],
     "measurement": "pd_rate",
     "query": "SELECT \"value\" FROM \"pd_rate\" WHERE \"disk_index\" = '$disk_index' AND \"fqdn\" = '$fqdn' AND $timeFilter GROUP BY \"controller\", \"type\", \"fqdn\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$fqdn" },
      { "condition": "AND", "key": "disk_index", "operator": "=", "value": "$disk_index" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "KiBps" }
     ]
    }
   ]
  },
  {
   "title": "IOPS on Physical Disk \"$disk_index\" of SFA \"$fqdn\"",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Controller $tag_controller",
     "groupBy": [
      { "params": [ "controller" ], "type": "tag" }
     ],
     "measurement": "pd_rate",
     "query": "SELECT \"value\" / $BARRELEYE_COLLECT_INTERVAL FROM \"pd_rate\" WHERE \"fqdn\" = '$fqdn' AND \"disk_index\" = '$disk_index' AND \"type\" = 'iops' AND $timeFilter GROUP BY \"controller\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$fqdn" },
      { "condition": "AND", "key": "disk_index", "operator": "=", "value": "$disk_index" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "iops" }
     ]
    }
   ]
  },
  {
   "title": "Bytes per I/O on Physical Disk \"$disk_index\" of SFA \"$fqdn\"",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "alias": "Controller $tag_controller",
     "groupBy": [
      { "params": [ "controller" ], "type": "tag" }
     ],
     "measurement": "pd_rate",
     "query": "SELECT \"value\" FROM \"vd_rate\" WHERE \"fqdn\" = 'OST' AND \"disk_index\" = '$disk_index' AND \"type\" = 'KiBps' AND $timeFilter GROUP BY \"controller\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$fqdn" },
      { "condition": "AND", "key": "disk_index", "operator": "=", "value": "$disk_index" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "KiBpIO" }
     ]
    }
   ]
  },
  {
   "title": "Write Performance on Physical Disk \"$disk_index\" of SFA \"$fqdn\"",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "alias": "Controller $tag_controller",
     "groupBy": [
      { "params": [ "controller" ], "type": "tag" }
     ],
     "measurement": "pd_rate",
     "query": "SELECT \"value\" FROM \"pd_rate\" WHERE \"fqdn\" = '$fqdn' AND \"disk_index\" = '$disk_index' AND \"type\" = 'W_KiBps' AND $timeFilter GROUP BY \"controller\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$fqdn" },
      { "condition": "AND", "key": "disk_index", "operator": "=", "value": "$disk_index" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "W_KiBps" }
     ]
    }
   ]
  },
  {
   "title": "Read Performance on Physical Disk \"$disk_index\" of SFA \"$fqdn\"",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "alias": "Controller $tag_controller",
     "groupBy": [
      { "params": [ "controller" ], "type": "tag" }
     ],
     "measurement": "pd_rate",
     "query": "SELECT \"value\" FROM \"pd_rate\" WHERE \"fqdn\" = '$fqdn' AND \"disk_index\" = '$disk_index' AND \"type\" = 'R_KiBps' AND $timeFilter GROUP BY \"controller\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$fqdn" },
      { "condition": "AND", "key": "disk_index", "operator": "=", "value": "$disk_index" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "R_KiBps" }
     ]
    }
   ]
  },
  {
   "title": "Write I/O Size Samples on Physical Disk \"$disk_index\" of SFA \"$fqdn\"",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "le4KiB",
     "measurement": "pd_iosize",
     "query": "SELECT \"value\" / $BARRELEYE_COLLECT_INTERVAL FROM \"pd_iosize\" WHERE \"fqdn\" = '$fqdn' AND \"disk_index\" = '$disk_index' AND \"type\" = 'write' AND \"iosize\" = 'le4KiB' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$fqdn" },
      { "condition": "AND", "key": "disk_index", "operator": "=", "value": "$disk_index" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "read" },
      { "condition": "AND", "key": "iosize", "operator": "=", "value": "le4KiB" }
     ]
    },
    {
     "alias": "le8KiB",
     "measurement": "pd_iosize",
     "query": "SELECT \"value\" / $BARRELEYE_COLLECT_INTERVAL FROM \"pd_iosize\" WHERE \"fqdn\" = '$fqdn' AND \"disk_index\" = '$disk_index' AND \"type\" = 'write' AND \"iosize\" = 'le8KiB' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$fqdn" },
      { "condition": "AND", "key": "disk_index", "operator": "=", "value": "$disk_index" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "read" },
      { "condition": "AND", "key": "iosize", "operator": "=", "value": "le8KiB" }
     ]
    },
    {
     "alias": "le16KiB",
     "measurement": "pd_iosize",
     "query": "SELECT \"value\" / $BARRELEYE_COLLECT_INTERVAL FROM \"pd_iosize\" WHERE \"fqdn\" = '$fqdn' AND \"disk_index\" = '$disk_index' AND \"type\" = 'write' AND \"iosize\" = 'le16KiB' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$fqdn" },
      { "condition": "AND", "key": "disk_index", "operator": "=", "value": "$disk_index" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "read" },
      { "condition": "AND", "key": "iosize", "operator": "=", "value": "le16KiB" }
     ]
    },
    {
     "alias": "le32KiB",
     "measurement": "pd_iosize",
     "query": "SELECT \"value\" / $BARRELEYE_COLLECT_INTERVAL FROM \"pd_iosize\" WHERE \"fqdn\" = '$fqdn' AND \"disk_index\" = '$disk_index' AND \"type\" = 'write' AND \"iosize\" = 'le32KiB' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$fqdn" },
      { "condition": "AND", "key": "disk_index", "operator": "=", "value": "$disk_index" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "read" },
      { "condition": "AND", "key": "iosize", "operator": "=", "value": "le32KiB" }
     ]
    },
    {
     "alias": "le64KiB",
     "measurement": "pd_iosize",
     "query": "SELECT \"value\" / $BARRELEYE_COLLECT_INTERVAL FROM \"pd_iosize\" WHERE \"fqdn\" = '$fqdn' AND \"disk_index\" = '$disk_index' AND \"type\" = 'write' AND \"iosize\" = 'le64KiB' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$fqdn" },
      { "condition": "AND", "key": "disk_index", "operator": "=", "value": "$disk_index" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "read" },
      { "condition": "AND", "key": "iosize", "operator": "=", "value": "le64KiB" }
     ]
    },
    {
     "alias": "le128KiB",
     "measurement": "pd_iosize",
     "query": "SELECT \"value\" / $BARRELEYE_COLLECT_INTERVAL FROM \"pd_iosize\" WHERE \"fqdn\" = '$fqdn' AND \"disk_index\" = '$disk_index' AND \"type\" = 'write' AND \"iosize\" = 'le128KiB' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$fqdn" },
      { "condition": "AND", "key": "disk_index", "operator": "=", "value": "$disk_index" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "read" },
      { "condition": "AND", "key": "iosize", "operator": "=", "value": "le128KiB" }
     ]
    },
    {
     "alias": "le256KiB",
     "measurement": "pd_iosize",
     "query": "SELECT \"value\" / $BARRELEYE_COLLECT_INTERVAL FROM \"pd_iosize\" WHERE \"fqdn\" = '$fqdn' AND \"disk_index\" = '$disk_index' AND \"type\" = 'write' AND \"iosize\" = 'le256KiB' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$fqdn" },
      { "condition": "AND", "key": "disk_index", "operator": "=", "value": "$disk_index" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "read" },
      { "condition": "AND", "key": "iosize", "operator": "=", "value": "le256KiB" }
     ]
    },
    {
     "alias": "le512KiB",
     "measurement": "pd_iosize",
     "query": "SELECT \"value\" / $BARRELEYE_COLLECT_INTERVAL FROM \"pd_iosize\" WHERE \"fqdn\" = '$fqdn' AND \"disk_index\" = '$disk_index' AND \"type\" = 'write' AND \"iosize\" = 'le512KiB' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$fqdn" },
      { "condition": "AND", "key": "disk_index", "operator": "=", "value": "$disk_index" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "read" },
      { "condition": "AND", "key": "iosize", "operator": "=", "value": "le512KiB" }
     ]
    },
    {
     "alias": "le1MiB",
     "measurement": "pd_iosize",
     "query": "SELECT \"value\" / $BARRELEYE_COLLECT_INTERVAL FROM \"pd_iosize\" WHERE \"fqdn\" = '$fqdn' AND \"disk_index\" = '$disk_index' AND \"type\" = 'write' AND \"iosize\" = 'le1MiB' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$fqdn" },
      { "condition": "AND", "key": "disk_index", "operator": "=", "value": "$disk_index" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "read" },
      { "condition": "AND", "key": "iosize", "operator": "=", "value": "le1MiB" }
     ]
    },
    {
     "alias": "le2MiB",
     "measurement": "pd_iosize",
     "query": "SELECT \"value\" / $BARRELEYE_COLLECT_INTERVAL FROM \"pd_iosize\" WHERE \"fqdn\" = '$fqdn' AND \"disk_index\" = '$disk_index' AND \"type\" = 'write' AND \"iosize\" = 'le2MiB' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$fqdn" },
      { "condition": "AND", "key": "disk_index", "operator": "=", "value": "$disk_index" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "read" },
      { "condition": "AND", "key": "iosize", "operator": "=", "value": "le2MiB" }
     ]
    },
    {
     "alias": "le4MiB",
     "measurement": "pd_iosize",
     "query": "SELECT \"value\" / $BARRELEYE_COLLECT_INTERVAL FROM \"pd_iosize\" WHERE \"fqdn\" = '$fqdn' AND \"disk_index\" = '$disk_index' AND \"type\" = 'write' AND \"iosize\" = 'le4MiB' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$fqdn" },
      { "condition": "AND", "key": "disk_index", "operator": "=", "value": "$disk_index" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "read" },
      { "condition": "AND", "key": "iosize", "operator": "=", "value": "le4MiB" }
     ]
    },
    {
     "alias": "gt4MiB",
     "measurement": "pd_iosize",
     "query": "SELECT \"value\" / $BARRELEYE_COLLECT_INTERVAL FROM \"pd_iosize\" WHERE \"fqdn\" = '$fqdn' AND \"disk_index\" = '$disk_index' AND \"type\" = 'write' AND \"iosize\" = 'gt4MiB' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$fqdn" },
      { "condition": "AND", "key": "disk_index", "operator": "=", "value": "$disk_index" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "read" },
      { "condition": "AND", "key": "iosize", "operator": "=", "value": "gt4MiB" }
     ]
    }
   ]
  },
  {
   "title": "Read I/O Size Samples on Physical Disk \"$disk_index\" of SFA \"$fqdn\"",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "le4KiB",
     "measurement": "pd_iosize",
     "query": "SELECT \"value\" / $BARRELEYE_COLLECT_INTERVAL FROM \"pd_iosize\" WHERE \"fqdn\" = '$fqdn' AND \"disk_index\" = '$disk_index' AND \"type\" = 'read' AND \"iosize\" = 'le4KiB' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$fqdn" },
      { "condition": "AND", "key": "disk_index", "operator": "=", "value": "$disk_index" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "read" },
      { "condition": "AND", "key": "iosize", "operator": "=", "value": "le4KiB" }
     ]
    },
    {
     "alias": "le8KiB",
     "measurement": "vd_iosize",
     "query": "SELECT \"value\" / $BARRELEYE_COLLECT_INTERVAL FROM \"pd_iosize\" WHERE \"fqdn\" = '$fqdn' AND \"disk_index\" = '$disk_index' AND \"type\" = 'read' AND \"iosize\" = 'le8KiB' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$fqdn" },
      { "condition": "AND", "key": "disk_index", "operator": "=", "value": "$disk_index" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "read" },
      { "condition": "AND", "key": "iosize", "operator": "=", "value": "le8KiB" }
     ]
    },
    {
     "alias": "le16KiB",
     "measurement": "vd_iosize",
     "query": "SELECT \"value\" / $BARRELEYE_COLLECT_INTERVAL FROM \"pd_iosize\" WHERE \"fqdn\" = '$fqdn' AND \"disk_index\" = '$disk_index' AND \"type\" = 'read' AND \"iosize\" = 'le16KiB' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$fqdn" },
      { "condition": "AND", "key": "disk_index", "operator": "=", "value": "$disk_index" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "read" },
      { "condition": "AND", "key": "iosize", "operator": "=", "value": "le16KiB" }
     ]
    },
    {
     "alias": "le32KiB",
     "measurement": "vd_iosize",
     "query": "SELECT \"value\" / $BARRELEYE_COLLECT_INTERVAL FROM \"pd_iosize\" WHERE \"fqdn\" = '$fqdn' AND \"disk_index\" = '$disk_index' AND \"type\" = 'read' AND \"iosize\" = 'le32KiB' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$fqdn" },
      { "condition": "AND", "key": "disk_index", "operator": "=", "value": "$disk_index" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "read" },
      { "condition": "AND", "key": "iosize", "operator": "=", "value": "le32KiB" }
     ]
    },
    {
     "alias": "le64KiB",
     "measurement": "vd_iosize",
     "query": "SELECT \"value\" / $BARRELEYE_COLLECT_INTERVAL FROM \"pd_iosize\" WHERE \"fqdn\" = '$fqdn' AND \"disk_index\" = '$disk_index' AND \"type\" = 'read' AND \"iosize\" = 'le64KiB' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$fqdn" },
      { "condition": "AND", "key": "disk_index", "operator": "=", "value": "$disk_index" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "read" },
      { "condition": "AND", "key": "iosize", "operator": "=", "value": "le64KiB" }
     ]
    },
    {
     "alias": "le128KiB",
     "measurement": "vd_iosize",
     "query": "SELECT \"value\" / $BARRELEYE_COLLECT_INTERVAL FROM \"pd_iosize\" WHERE \"fqdn\" = '$fqdn' AND \"disk_index\" = '$disk_index' AND \"type\" = 'read' AND \"iosize\" = 'le128KiB' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$fqdn" },
      { "condition": "AND", "key": "disk_index", "operator": "=", "value": "$disk_index" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "read" },
      { "condition": "AND", "key": "iosize", "operator": "=", "value": "le128KiB" }
     ]
    },
    {
     "alias": "le256KiB",
     "measurement": "vd_iosize",
     "query": "SELECT \"value\" / $BARRELEYE_COLLECT_INTERVAL FROM \"pd_iosize\" WHERE \"fqdn\" = '$fqdn' AND \"disk_index\" = '$disk_index' AND \"type\" = 'read' AND \"iosize\" = 'le256KiB' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$fqdn" },
      { "condition": "AND", "key": "disk_index", "operator": "=", "value": "$disk_index" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "read" },
      { "condition": "AND", "key": "iosize", "operator": "=", "value": "le256KiB" }
     ]
    },
    {
     "alias": "le512KiB",
     "measurement": "vd_iosize",
     "query": "SELECT \"value\" / $BARRELEYE_COLLECT_INTERVAL FROM \"pd_iosize\" WHERE \"fqdn\" = '$fqdn' AND \"disk_index\" = '$disk_index' AND \"type\" = 'read' AND \"iosize\" = 'le512KiB' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$fqdn" },
      { "condition": "AND", "key": "disk_index", "operator": "=", "value": "$disk_index" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "read" },
      { "condition": "AND", "key": "iosize", "operator": "=", "value": "le512KiB" }
     ]
    },
    {
     "alias": "le1MiB",
     "measurement": "vd_iosize",
     "query": "SELECT \"value\" / $BARRELEYE_COLLECT_INTERVAL FROM \"pd_iosize\" WHERE \"fqdn\" = '$fqdn' AND \"disk_index\" = '$disk_index' AND \"type\" = 'read' AND \"iosize\" = 'le1MiB' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$fqdn" },
      { "condition": "AND", "key": "disk_index", "operator": "=", "value": "$disk_index" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "read" },
      { "condition": "AND", "key": "iosize", "operator": "=", "value": "le1MiB" }
     ]
    },
    {
     "alias": "le2MiB",
     "measurement": "vd_iosize",
     "query": "SELECT \"value\" / $BARRELEYE_COLLECT_INTERVAL FROM \"pd_iosize\" WHERE \"fqdn\" = '$fqdn' AND \"disk_index\" = '$disk_index' AND \"type\" = 'read' AND \"iosize\" = 'le2MiB' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$fqdn" },
      { "condition": "AND", "key": "disk_index", "operator": "=", "value": "$disk_index" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "read" },
      { "condition": "AND", "key": "iosize", "operator": "=", "value": "le2MiB" }
     ]
    },
    {
     "alias": "le4MiB",
     "measurement": "vd_iosize",
     "query": "SELECT \"value\" / $BARRELEYE_COLLECT_INTERVAL FROM \"pd_iosize\" WHERE \"fqdn\" = '$fqdn' AND \"disk_index\" = '$disk_index' AND \"type\" = 'read' AND \"iosize\" = 'le4MiB' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$fqdn" },
      { "condition": "AND", "key": "disk_index", "operator": "=", "value": "$disk_index" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "read" },
      { "condition": "AND", "key": "iosize", "operator": "=", "value": "le4MiB" }
     ]
    },
    {
     "alias": "gt4MiB",
     "measurement": "vd_iosize",
     "query": "SELECT \"value\" / $BARRELEYE_COLLECT_INTERVAL FROM \"pd_iosize\" WHERE \"fqdn\" = '$fqdn' AND \"disk_index\" = '$disk_index' AND \"type\" = 'read' AND \"iosize\" = 'gt4MiB' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$fqdn" },
      { "condition": "AND", "key": "disk_index", "operator": "=", "value": "$disk_index" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "read" },
      { "condition": "AND", "key": "iosize", "operator": "=", "value": "gt4MiB" }
     ]
    }
   ]
  },
  {
   "title": "Write Latency Samples on Physical Disk \"$disk_index\" of SFA \"$fqdn\"",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "le4ms",
     "measurement": "pd_latency",
     "query": "SELECT \"value\" / $BARRELEYE_COLLECT_INTERVAL FROM \"pd_latency\" WHERE \"fqdn\" = '$fqdn' AND \"disk_index\" = '$disk_index' AND \"type\" = 'write' AND \"latency\" = 'le4ms' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$fqdn" },
      { "condition": "AND", "key": "disk_index", "operator": "=", "value": "$disk_index" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "write" },
      { "condition": "AND", "key": "latency", "operator": "=", "value": "le4ms" }
     ]
    },
    {
     "alias": "le8ms",
     "measurement": "pd_latency",
     "query": "SELECT \"value\" / $BARRELEYE_COLLECT_INTERVAL FROM \"pd_latency\" WHERE \"fqdn\" = '$fqdn' AND \"disk_index\" = '$disk_index' AND \"type\" = 'write' AND \"latency\" = 'le8ms' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$fqdn" },
      { "condition": "AND", "key": "disk_index", "operator": "=", "value": "$disk_index" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "write" },
      { "condition": "AND", "key": "latency", "operator": "=", "value": "le8ms" }
     ]
    },
    {
     "alias": "le16ms",
     "measurement": "pd_latency",
     "query": "SELECT \"value\" / $BARRELEYE_COLLECT_INTERVAL FROM \"pd_latency\" WHERE \"fqdn\" = '$fqdn' AND \"disk_index\" = '$disk_index' AND \"type\" = 'write' AND \"latency\" = 'le16ms' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$fqdn" },
      { "condition": "AND", "key": "disk_index", "operator": "=", "value": "$disk_index" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "write" },
      { "condition": "AND", "key": "latency", "operator": "=", "value": "le16ms" }
     ]
    },
    {
     "alias": "le32ms",
     "measurement": "pd_latency",
     "query": "SELECT \"value\" / $BARRELEYE_COLLECT_INTERVAL FROM \"pd_latency\" WHERE \"fqdn\" = '$fqdn' AND \"disk_index\" = '$disk_index' AND \"type\" = 'write' AND \"latency\" = 'le32ms' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$fqdn" },
      { "condition": "AND", "key": "disk_index", "operator": "=", "value": "$disk_index" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "write" },
      { "condition": "AND", "key": "latency", "operator": "=", "value": "le32ms" }
     ]
    },
    {
     "alias": "le64ms",
     "measurement": "pd_latency",
     "query": "SELECT \"value\" / $BARRELEYE_COLLECT_INTERVAL FROM \"pd_latency\" WHERE \"fqdn\" = '$fqdn' AND \"disk_index\" = '$disk_index' AND \"type\" = 'write' AND \"latency\" = 'le64ms' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$fqdn" },
      { "condition": "AND", "key": "disk_index", "operator": "=", "value": "$disk_index" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "write" },
      { "condition": "AND", "key": "latency", "operator": "=", "value": "le64ms" }
     ]
    },
    {
     "alias": "le128ms",
     "measurement": "pd_latency",
     "query": "SELECT \"value\" / $BARRELEYE_COLLECT_INTERVAL FROM \"pd_latency\" WHERE \"fqdn\" = '$fqdn' AND \"disk_index\" = '$disk_index' AND \"type\" = 'write' AND \"latency\" = 'le128ms' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$fqdn" },
      { "condition": "AND", "key": "disk_index", "operator": "=", "value": "$disk_index" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "write" },
      { "condition": "AND", "key": "latency", "operator": "=", "value": "le128ms" }
     ]
    },
    {
     "alias": "le256ms",
     "measurement": "pd_latency",
     "query": "SELECT \"value\" / $BARRELEYE_COLLECT_INTERVAL FROM \"pd_latency\" WHERE \"fqdn\" = '$fqdn' AND \"disk_index\" = '$disk_index' AND \"type\" = 'write' AND \"latency\" = 'le256ms' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$fqdn" },
      { "condition": "AND", "key": "disk_index", "operator": "=", "value": "$disk_index" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "write" },
      { "condition": "AND", "key": "latency", "operator": "=", "value": "le256ms" }
     ]
    },
    {
     "alias": "le512ms",
     "measurement": "pd_latency",
     "query": "SELECT \"value\" / $BARRELEYE_COLLECT_INTERVAL FROM \"pd_latency\" WHERE \"fqdn\" = '$fqdn' AND \"disk_index\" = '$disk_index' AND \"type\" = 'write' AND \"latency\" = 'le512ms' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$fqdn" },
      { "condition": "AND", "key": "disk_index", "operator": "=", "value": "$disk_index" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "write" },
      { "condition": "AND", "key": "latency", "operator": "=", "value": "le512ms" }
     ]
    },
    {
     "alias": "le1s",
     "measurement": "pd_latency",
     "query": "SELECT \"value\" / $BARRELEYE_COLLECT_INTERVAL FROM \"pd_latency\" WHERE \"fqdn\" = '$fqdn' AND \"disk_index\" = '$disk_index' AND \"type\" = 'write' AND \"latency\" = 'le1s' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$fqdn" },
      { "condition": "AND", "key": "disk_index", "operator": "=", "value": "$disk_index" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "write" },
      { "condition": "AND", "key": "latency", "operator": "=", "value": "le1s" }
     ]
    },
    {
     "alias": "le2s",
     "measurement": "pd_latency",
     "query": "SELECT \"value\" / $BARRELEYE_COLLECT_INTERVAL FROM \"pd_latency\" WHERE \"fqdn\" = '$fqdn' AND \"disk_index\" = '$disk_index' AND \"type\" = 'write' AND \"latency\" = 'le2s' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$fqdn" },
      { "condition": "AND", "key": "disk_index", "operator": "=", "value": "$disk_index" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "write" },
      { "condition": "AND", "key": "latency", "operator": "=", "value": "le2s" }
     ]
    },
    {
     "alias": "le4s",
     "measurement": "pd_latency",
     "query": "SELECT \"value\" / $BARRELEYE_COLLECT_INTERVAL FROM \"pd_latency\" WHERE \"fqdn\" = '$fqdn' AND \"disk_index\" = '$disk_index' AND \"type\" = 'write' AND \"latency\" = 'le4s' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$fqdn" },
      { "condition": "AND", "key": "disk_index", "operator": "=", "value": "$disk_index" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "write" },
      { "condition": "AND", "key": "latency", "operator": "=", "value": "le4s" }
     ]
    },
    {
     "alias": "gt4s",
     "measurement": "pd_latency",
     "query": "SELECT \"value\" / $BARRELEYE_COLLECT_INTERVAL FROM \"pd_latency\" WHERE \"fqdn\" = '$fqdn' AND \"disk_index\" = '$disk_index' AND \"type\" = 'write' AND \"latency\" = 'gt4s' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$fqdn" },
      { "condition": "AND", "key": "disk_index", "operator": "=", "value": "$disk_index" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "write" },
      { "condition": "AND", "key": "latency", "operator": "=", "value": "gt4s" }
     ]
    }
   ]
  },
  {
   "title": "Read Latency Samples on Physical Disk \"$disk_index\" of SFA \"$fqdn\"",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "le4ms",
     "measurement": "pd_latency",
     "query": "SELECT \"value\" / $BARRELEYE_COLLECT_INTERVAL FROM \"pd_latency\" WHERE \"fqdn\" = '$fqdn' AND \"disk_index\" = '$disk_index' AND \"type\" = 'read' AND \"latency\" = 'le4ms' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$fqdn" },
      { "condition": "AND", "key": "disk_index", "operator": "=", "value": "$disk_index" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "read" },
      { "condition": "AND", "key": "latency", "operator": "=", "value": "le4ms" }
     ]
    },
    {
     "alias": "le8ms",
     "measurement": "pd_latency",
     "query": "SELECT \"value\" / $BARRELEYE_COLLECT_INTERVAL FROM \"pd_latency\" WHERE \"fqdn\" = '$fqdn' AND \"disk_index\" = '$disk_index' AND \"type\" = 'read' AND \"latency\" = 'le8ms' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$fqdn" },
      { "condition": "AND", "key": "disk_index", "operator": "=", "value": "$disk_index" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "read" },
      { "condition": "AND", "key": "latency", "operator": "=", "value": "le8ms" }
     ]
    },
    {
     "alias": "le16ms",
     "measurement": "pd_latency",
     "query": "SELECT \"value\" / $BARRELEYE_COLLECT_INTERVAL FROM \"pd_latency\" WHERE \"fqdn\" = '$fqdn' AND \"disk_index\" = '$disk_index' AND \"type\" = 'read' AND \"latency\" = 'le16ms' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$fqdn" },
      { "condition": "AND", "key": "disk_index", "operator": "=", "value": "$disk_index" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "read" },
      { "condition": "AND", "key": "latency", "operator": "=", "value": "le16ms" }
     ]
    },
    {
     "alias": "le32ms",
     "measurement": "pd_latency",
     "query": "SELECT \"value\" / $BARRELEYE_COLLECT_INTERVAL FROM \"pd_latency\" WHERE \"fqdn\" = '$fqdn' AND \"disk_index\" = '$disk_index' AND \"type\" = 'read' AND \"latency\" = 'le32ms' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$fqdn" },
      { "condition": "AND", "key": "disk_index", "operator": "=", "value": "$disk_index" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "read" },
      { "condition": "AND", "key": "latency", "operator": "=", "value": "le32ms" }
     ]
    },
    {
     "alias": "le64ms",
     "measurement": "pd_latency",
     "query": "SELECT \"value\" / $BARRELEYE_COLLECT_INTERVAL FROM \"pd_latency\" WHERE \"fqdn\" = '$fqdn' AND \"disk_index\" = '$disk_index' AND \"type\" = 'read' AND \"latency\" = 'le64ms' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$fqdn" },
      { "condition": "AND", "key": "disk_index", "operator": "=", "value": "$disk_index" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "read" },
      { "condition": "AND", "key": "latency", "operator": "=", "value": "le64ms" }
     ]
    },
    {
     "alias": "le128ms",
     "measurement": "pd_latency",
     "query": "SELECT \"value\" / $BARRELEYE_COLLECT_INTERVAL FROM \"pd_latency\" WHERE \"fqdn\" = '$fqdn' AND \"disk_index\" = '$disk_index' AND \"type\" = 'read' AND \"latency\" = 'le128ms' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$fqdn" },
      { "condition": "AND", "key": "disk_index", "operator": "=", "value": "$disk_index" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "read" },
      { "condition": "AND", "key": "latency", "operator": "=", "value": "le128ms" }
     ]
    },
    {
     "alias": "le256ms",
     "measurement": "pd_latency",
     "query": "SELECT \"value\" / $BARRELEYE_COLLECT_INTERVAL FROM \"pd_latency\" WHERE \"fqdn\" = '$fqdn' AND \"disk_index\" = '$disk_index' AND \"type\" = 'read' AND \"latency\" = 'le256ms' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$fqdn" },
      { "condition": "AND", "key": "disk_index", "operator": "=", "value": "$disk_index" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "read" },
      { "condition": "AND", "key": "latency", "operator": "=", "value": "le256ms" }
     ]
    },
    {
     "alias": "le512ms",
     "measurement": "pd_latency",
     "query": "SELECT \"value\" / $BARRELEYE_COLLECT_INTERVAL FROM \"pd_latency\" WHERE \"fqdn\" = '$fqdn' AND \"disk_index\" = '$disk_index' AND \"type\" = 'read' AND \"latency\" = 'le512ms' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$fqdn" },
      { "condition": "AND", "key": "disk_index", "operator": "=", "value": "$disk_index" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "read" },
      { "condition": "AND", "key": "latency", "operator": "=", "value": "le512ms" }
     ]
    },
    {
     "alias": "le1s",
     "measurement": "pd_latency",
     "query": "SELECT \"value\" / $BARRELEYE_COLLECT_INTERVAL FROM \"pd_latency\" WHERE \"fqdn\" = '$fqdn' AND \"disk_index\" = '$disk_index' AND \"type\" = 'read' AND \"latency\" = 'le1s' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$fqdn" },
      { "condition": "AND", "key": "disk_index", "operator": "=", "value": "$disk_index" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "read" },
      { "condition": "AND", "key": "latency", "operator": "=", "value": "le1s" }
     ]
    },
    {
     "alias": "le2s",
     "measurement": "pd_latency",
     "query": "SELECT \"value\" / $BARRELEYE_COLLECT_INTERVAL FROM \"pd_latency\" WHERE \"fqdn\" = '$fqdn' AND \"disk_index\" = '$disk_index' AND \"type\" = 'read' AND \"latency\" = 'le2s' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$fqdn" },
      { "condition": "AND", "key": "disk_index", "operator": "=", "value": "$disk_index" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "read" },
      { "condition": "AND", "key": "latency", "operator": "=", "value": "le2s" }
     ]
    },
    {
     "alias": "le4s",
     "measurement": "pd_latency",
     "query": "SELECT \"value\" / $BARRELEYE_COLLECT_INTERVAL FROM \"pd_latency\" WHERE \"fqdn\" = '$fqdn' AND \"disk_index\" = '$disk_index' AND \"type\" = 'read' AND \"latency\" = 'le4s' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$fqdn" },
      { "condition": "AND", "key": "disk_index", "operator": "=", "value": "$disk_index" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "read" },
      { "condition": "AND", "key": "latency", "operator": "=", "value": "le4s" }
     ]
    },
    {
     "alias": "gt4s",
     "measurement": "pd_latency",
     "query": "SELECT \"value\" / $BARRELEYE_COLLECT_INTERVAL FROM \"pd_latency\" WHERE \"fqdn\" = '$fqdn' AND \"disk_index\" = '$disk_index' AND \"type\" = 'read' AND \"latency\" = 'gt4s' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$fqdn" },
      { "condition": "AND", "key": "disk_index", "operator": "=", "value": "$disk_index" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "read" },
      { "condition": "AND", "key": "latency", "operator": "=", "value": "gt4s" }
     ]
    }
   ]
  },
  {
   "title": "Forwarding I/O Performance on Physical Disk \"$disk_index\" of SFA \"$fqdn\"",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "alias": "Controller $tag_controller",
     "groupBy": [
      { "params": [ "controller" ], "type": "tag" }
     ],
     "measurement": "pd_rate",
     "query": "SELECT \"value\" FROM \"pd_rate\" WHERE \"fqdn\" = '$fqdn' AND \"disk_index\" = '$disk_index' AND \"type\" = 'Fwd_KiBps' AND $timeFilter GROUP BY \"controller\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$fqdn" },
      { "condition": "AND", "key": "disk_index", "operator": "=", "value": "$disk_index" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Fwd_KiBps" }
     ]
    }
   ]
  },
  {
   "title": "Forwarding IOPS on Physical Disk \"$disk_index\" of SFA \"$fqdn\"",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "alias": "Controller $tag_controller",
     "groupBy": [
      { "params": [ "controller" ], "type": "tag" }
     ],
     "measurement": "pd_rate",
     "query": "SELECT \"value\" FROM \"pd_rate\" WHERE \"fqdn\" = '$fqdn' AND \"disk_index\" = '$disk_index' AND \"type\" = 'Fwd_iops' AND $timeFilter GROUP BY \"controller\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fqdn", "operator": "=", "value": "$fqdn" },
      { "condition": "AND", "key": "disk_index", "operator": "=", "value": "$disk_index" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Fwd_iops" }
     ]
    }
   ]
  }
 ]
}